oppo-a51f: add nt35592 display panel support
msm8916-mainline/linux pull request #107
Opened 2020-09-29 04:17 UTC by Hinokami-Kagura

2020-09-29 08:12 UTC, Hinokami-Kagura commented
dmesg : https://gitlab.com/-/snippets/2020103

can I refer the wt88047 setting to use on my phone model? many thanks!

2020-09-29 15:33 UTC, Minecrell requested changes

2020-09-29 15:33 UTC, Minecrell commented on drivers/gpu/drm/panel/panel-oppo15009jdi-nt35592.c
> +	{ .compatible = "mdss,oppo15009jdi-nt35592" }, // FIXME
I think this would be better as something like

```suggestion
	{ .compatible = "oppo,15009-nt35592-jdi" },
```

2020-09-29 15:33 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +		/*backlight = <&backlight>;*/
```suggestion
```

Remove this for now, add it back later when you work on it.

Also, I believe your display requires the `pm8916_l17` regulator as seen here: https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/308d74dfeefe473b5234fb82b4b6b39c9ec06a2c/arch/arm/boot/dts/15009/msm8916-mdss.dtsi#L126

So you should regenerate your panel driver with the `--regulator power` option and then add:

```
power-supply = <&pm8916_l17>;
```

2020-09-29 15:33 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	mdss {
Keep this alphabetically ordered, i.e. move `mdss` before `sd_vmmc_en_default`.

2020-09-29 15:50 UTC, Hinokami-Kagura commented on drivers/gpu/drm/panel/panel-oppo15009jdi-nt35592.c
> +	{ .compatible = "mdss,oppo15009jdi-nt35592" }, // FIXME
okok, this is better, but need remember to modify in dts also...XD

2020-09-29 16:28 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +		/*backlight = <&backlight>;*/
Thanks for reminding, I've added related source about it.

2020-09-29 17:37 UTC, Minecrell commented on drivers/gpu/drm/panel/panel-oppo15009jdi-nt35592.c
> +	}*/
@Hinokami-Kagura Can you squash the commit so that there are only two commits:

- `drm/panel: add ...`
- `arm64: dts: qcom: msm8916-oppo-a51f: Add display`

Also, there is no need to keep these code suggestions here, clearly they were wrong. Just keep the generated panel driver mostly as-is. Thanks :)

2020-09-29 18:19 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	power-supply = <&pm8916_l17>;
Sorry, this should be part of the panel@0 node :D

2020-09-29 18:35 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	power-supply = <&pm8916_l17>;
and removed here? :D

2020-09-30 07:52 UTC, Minecrell approved these changes

2020-10-01 12:03 UTC, Minecrell commented
I will close this one and instead review #110 since you included all other changes there.

2020-10-01 12:03 UTC, closed without merging