Add support for PM8916 charger and bms
msm8916-mainline/linux pull request #112
Opened 2020-10-05 08:14 UTC by TravMurav

This PR adds support for:

1. pm8916 lbc-charger
This is a relatively simple driver that sets voltage and current target in lbc, then hardware will automatically charge the battery.
It seems like downstream driver disables lbc when it thinks that battery has been fully charged but it relies on bms so I decided not to implement this. I'm leaving everything to the hardware. It uses maximum allowed current in CC mode then in CV mode it starts reducing the current. Since lbc is not disabled it will keep powering the device. Flowchart in pm8916 Device Specification, page 33 shows that lbc automatically stops charging so I assume that it should be safe to leave it as is. I observed ~5mA current via usb when device is fully charged and display is off. It increases when display is turned on so I suppose that the device itself consumes some current via USB.

2. pm8916 vm-bms
This driver adds battery capacity monitoring via pmic features.
As I understand, pmic can measure OCV (Open-circuit voltage - can show real battery capacity) only on boot and in sleep. As I suppose - boot is when battery is inserted and pmic is turned on and sleep is when pmic is powered but the device is turned off. This means that I can only get OCV on boot. This driver gets boot OCV and then makes some assumptions to estimate it:
    * When charger is online, ocv can only increase
    * When charger is offline, ocv can only decrease and ocv > vbat
    * ocv can't change more than 0.025v between the measurements
    * When charger is in CV mode (vbat = const vbat-max), ocv increases by 0.004v every measurement until it reaches vbat
All of this gives me somewhat realistic (but pessimistic) estimation of battery capacity.

I'm using battery OCV table from downstream - it seems to be good enough.
I've added extcon support to lbc but didn't enable it in the dt yet

2020-10-13 17:23 UTC, Minecrell commented on drivers/power/supply/pm8916_bms_vm.c
> +		return IRQ_HANDLED;
This looks a bit like "if charger fails to return status, return" but this does not really make sense to me. What's the reason for this check?

2020-10-13 17:23 UTC, Minecrell commented on drivers/power/supply/pm8916_bms_vm.c
> +				 bat->reg + PM8916_BMS_VM_BMS_FIFO_REG_0_LSB + i * 2, &tmp, 2);
I wonder if we can read both FIFOs in one call of `regmap_bulk_read`, given that they are consecutive.

2020-10-13 17:23 UTC, Minecrell commented on drivers/power/supply/pm8916_lbc_chgr.c
> +			   PM8916_LBC_CHGR_CHG_EN | PM8916_LBC_CHGR_PSTG_EN);
Perhaps we should add some error checks in this function

2020-10-13 17:23 UTC, Minecrell commented on drivers/power/supply/pm8916_lbc_chgr.c
> +				  chg->reg[LBC_CHGR] + PM8916_LBC_CHGR_CHG_STATUS, &tmp);
This read seems pointless?

2020-10-13 17:23 UTC, Minecrell commented on drivers/power/supply/pm8916_lbc_chgr.c
> +	of_property_read_u32_array(dev->of_node, "reg", chg->reg, len);
Error check?

2020-10-13 17:23 UTC, Minecrell commented on drivers/power/supply/pm8916_lbc_chgr.c
> +	dev_warn(dev, "Do you have a class D fire extinguisher?\n");
I'm not sure if we want to require everyone using the mainline kernel to have this. I mean, it's good to have but maybe you don't have it with you all the time.

2020-10-13 17:23 UTC, Minecrell commented on drivers/power/supply/pm8916_bms_vm.c
> +		ret = devm_request_irq(dev, irq, pm8916_bms_vm_fifo_update_done_irq,
Perhaps using a threaded interrupt (`request_threaded_irq`) would be better. regmap can block theoretically while someone else is reading, which would be really bad with interrupts disabled.

2020-10-14 08:26 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +		compatible = "qcom,pm8916-lbc-chgr";
HRD calls it `LBC_CHGR` so I decided to use their name. Can change it.

2020-10-14 08:28 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +		qcom,bms-vm-s2-sample-interval = <100>;
In the beginning I was planning to expose all of those settings into DT but now I think it won't help much. Will drop those - makes everything a bit simpler

2020-10-14 08:30 UTC, TravMurav commented on drivers/power/supply/Kconfig
> +        depends on MFD_PM8XXX || MFD_SPMI_PMIC
Thanks, I copied it from somewhere without knowing if it's actually what I need.

2020-10-14 08:36 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +		compatible = "qcom,pm8916-lbc-chgr";
I think this is because the registers are like

`LBC_<subtype>`, where `<subtype>` is one of `CHGR`, `BAT_IF`, `USB`, `MISC`. The overall system seems to be called LBC.

2020-10-14 08:37 UTC, TravMurav commented on drivers/power/supply/pm8916_bms_vm.c
> +	case POWER_SUPPLY_PROP_STATUS:
In my laptop charger only reports `online` property. BMS reports this one.

2020-10-14 08:41 UTC, TravMurav commented on drivers/power/supply/pm8916_bms_vm.c
> +		return IRQ_HANDLED;
If we don't know whether system is charging or not, we can't process new data - (we make some assumptions based on this state) and as I understand, isr should always return `IRQ_HANDLED`
I guess it's not the best thing but not sure about any other way to handle this situation

2020-10-14 08:42 UTC, TravMurav commented on drivers/power/supply/pm8916_bms_vm.c
> +				 bat->reg + PM8916_BMS_VM_BMS_FIFO_REG_0_LSB + i * 2, &tmp, 2);
I could probably make some `u16` array of fixed size (from macro) and read into it

2020-10-14 08:48 UTC, TravMurav commented on drivers/power/supply/pm8916_lbc_chgr.c
> +				  chg->reg[LBC_CHGR] + PM8916_LBC_CHGR_CHG_STATUS, &tmp);
Ah, I guess I was going to add additional check for `CHG_ON`

2020-10-14 08:48 UTC, TravMurav commented on drivers/power/supply/pm8916_lbc_chgr.c
> +	dev_warn(dev, "Do you have a class D fire extinguisher?\n");
Will drop :)

2020-10-14 08:51 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +		compatible = "qcom,pm8916-lbc-chgr";
Ah, I guess then since I'm representing all of them, I should rename it

2020-10-16 19:51 UTC, Minecrell commented on drivers/power/supply/pm8916_bms_vm.c
> +	case POWER_SUPPLY_PROP_STATUS:
Well, it seems like BMS doesn't really have the information required for this so if tools can handle it I think it would be more appropriate in the charger driver...

2020-10-16 19:52 UTC, Minecrell commented on drivers/power/supply/pm8916_bms_vm.c
> +		return IRQ_HANDLED;
Hmm ok.

2020-10-22 15:56 UTC, TravMurav commented on drivers/power/supply/pm8916_bms_vm.c
> +	case POWER_SUPPLY_PROP_STATUS:
Reporting this (and some other values) from charger makes userspace daemons sad: It either reports state incorrectly or thinks there is *two* batteries in the system (with second being lbc)

2020-10-22 16:09 UTC, TravMurav commented on drivers/power/supply/pm8916_bms_vm.c
> +	case POWER_SUPPLY_PROP_STATUS:
(Repeating this message because I don't see it there) If I report this from lbc, userspace becomes sad and reports state incorrectly.

2020-10-22 16:16 UTC, TravMurav commented on drivers/power/supply/pm8916_lbc_chgr.c
> +	of_property_read_u32_array(dev->of_node, "reg", chg->reg, len);
Won't it fail on `len = of_property_count_u32_elems(dev->of_node, "reg");`?

2020-10-23 15:59 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +			<3555000 3>, <3475000 2>, <3356000 1>, <3000000 0>;
This is just a table <OCV; Capacity%>
Those are from downstream, just adapted and simplified a bit. It could probably be tweaked a bit but it will take too much time to be worth it. 
In downstream it is this: 
https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/wileyfox-crackling/arch/arm/boot/dts/qcom/l8150/batterydata-l8150-jd-4v35-2500mah.dtsi#L16-L56

I only used column for 25 (*C) since my bms doesn't know real battery temperature

2020-10-23 17:19 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +			<3555000 3>, <3475000 2>, <3356000 1>, <3000000 0>;
> I only used column for 25 (*C) since my bms doesn't know real battery temperature

Would that be hard to implement or do they just guess it?

2020-10-23 17:23 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/pm8916.dtsi
> +		pm8916_charger: lbc-charger@1000 {
Device tree nodes should be (preferably) generic. Not sure about the vm-bms one yet...

```suggestion
		pm8916_charger: charger@1000 {
```

2020-10-23 17:23 UTC, Minecrell commented on drivers/power/supply/pm8916_lbc.c
> +	ret = regmap_write(chg->regmap, chg->reg[LBC_CHGR] + PM8916_LBC_CHGR_VDD_SAFE, tmp);
error checks here?

2020-10-23 17:23 UTC, Minecrell commented on drivers/power/supply/pm8916_bms_vm.c
> +			   bat->reg + PM8916_BMS_VM_MODE_CTL, PM8916_BMS_VM_MODE_FORCE_S3);
error checks maybe?

2020-10-24 07:24 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +			<3555000 3>, <3475000 2>, <3356000 1>, <3000000 0>;
Hmmm, I'll need to figure out how to get that adc channel
https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/b20608408caff817ec874f325127b07609fbaeb8/drivers/power/qpnp-vm-bms.c#L1218-L1235

Not sure if it will be enough to just add another channel for `LR_MUX1_BATT_THERM` there
https://github.com/msm8916-mainline/linux/blob/master/arch/arm64/boot/dts/qcom/pm8916.dtsi#L53-L84

If adc will just work then I don't think it will be that hard to implement

2020-10-24 07:27 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +			<3555000 3>, <3475000 2>, <3356000 1>, <3000000 0>;
I didn't really looked into this because curves for my battery seems to be very similar to each other.

![Screenshot_20201024_122529](https://user-images.githubusercontent.com/22081178/97070727-10068b80-15f4-11eb-9d00-8c0e1a71776f.png)

2020-10-24 09:43 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +			<3555000 3>, <3475000 2>, <3356000 1>, <3000000 0>;
Might need to add some scale here to make it work properly: https://github.com/msm8916-mainline/linux/blob/48cc8d930cb544b00cbdcf288ee17a02912d34fd/drivers/iio/adc/qcom-spmi-vadc.c#L600

2020-10-24 11:03 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +			<3555000 3>, <3475000 2>, <3356000 1>, <3000000 0>;
If raw-to-temp scaling is device specific then I have no idea how to implement it - It probably configured somewhere there 
https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/wileyfox-crackling/arch/arm/boot/dts/qcom/msm8916-qrd-l8150.dts#L166-L189
but I'm not sure how yet

2020-10-24 17:24 UTC, Minecrell commented on drivers/power/supply/pm8916_lbc_chgr.c
> +	of_property_read_u32_array(dev->of_node, "reg", chg->reg, len);
There could be weird errors happening for some reason, I think it's better to be safe here.

2020-10-24 17:24 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +			<3555000 3>, <3475000 2>, <3356000 1>, <3000000 0>;
Hmm okay, perhaps something for later/never.

2020-10-24 17:50 UTC, Minecrell commented on drivers/power/supply/pm8916_bms_vm.c
> +			 &vbat_data, PM8916_BMS_VM_FIFO_COUNT * 2);
at least here an error check would be good so you don't start working on garbage data

2020-10-24 17:50 UTC, Minecrell commented on drivers/power/supply/pm8916_bms_vm.c
> +			       bat->reg + PM8916_BMS_VM_S3_S7_OCV_DATA0, &tmp, 2);
I keep seeing things where I think that an error check would be useful to make sure that we don't do stupid stuff when an error happens. Also, the code just looks weird if you assign ret but don't do anything with it. Maybe it's easiest if you just add error checks everywhere where regmap is used.

2020-10-24 17:50 UTC, Minecrell commented on drivers/power/supply/pm8916_bms_vm.c
> +		supplied = power_supply_is_system_supplied();
Perhaps using `power_supply_am_i_supplied` would be nicer at least? I think there might be some way to make the power supply core aware of the mapping between vm-bms and lbc.

2020-10-24 17:50 UTC, Minecrell commented on drivers/power/supply/pm8916_bms_vm.c
> +	//FIXME: Should I check this pm event?
I think we should do something about this FIXME.

2020-10-24 17:50 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +	qcom,lbc-chgr-tchg-max = <0>;
Maybe we should set some time here? Also, the `lbc-chgr` is also kind of weird here. But perhaps even `qcom,vdd-safe` would be enough

2020-10-24 17:50 UTC, Minecrell commented on drivers/power/supply/pm8916_lbc.c
> +		ret = devm_request_irq(dev, irq, pm8916_lbc_charger_state_changed_irq,
perhaps this should be also threaded?

2020-10-29 09:45 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +	qcom,lbc-chgr-tchg-max = <0>;
~~Maximum there is `0x3F: TCHG_MAX_256MIN` (\~4 hrs) and~~ crackling with current limit that we have now already takes 3-4 hours from 0 to 100 (according to an external-fuel-gauge-thingie) It will charge even longer on slow charger (e.g. connected to a pc) - this means I need to handle `CHG_FAILED` and I'm not sure how yet

p.s. Not sure why HRD says `[ range = 4 min to 8 hr 32 min ]` which corresponds to 7 bits they allow but only list half of the values. They seem to love putting all of them usually.

2020-10-29 13:37 UTC, TravMurav commented on drivers/power/supply/pm8916_bms_vm.c
> +	//FIXME: Should I check this pm event?
I guess I don't since quick grep shows that no one does and I think it will only send `PM_EVENT_SUSPEND` anyway

2020-10-30 11:20 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +	qcom,lbc-chgr-tchg-max = <0>;
I've been meaning this ask this actually: How is the current limit controlled atm? iirc downstream sets it based on USB cable detection (i.e. it limits current when connected to a PC and sets higher possible current for AC adapters).

2020-10-30 11:24 UTC, Minecrell commented on drivers/power/supply/pm8916_bms_vm.c
> +	bat = platform_get_drvdata(pdev);
you can inline this above,

```c
struct pm8916_bms_vm_battery *bat = platform_get_drvdata(pdev);
```

2020-10-30 11:24 UTC, Minecrell commented on drivers/power/supply/pm8916_bms_vm.c
> +	bat = platform_get_drvdata(pdev);
same here

2020-10-30 11:24 UTC, Minecrell commented on drivers/power/supply/pm8916_lbc.c
> +		val->intval = (bool)(tmp & PM8916_LBC_USB_USBIN_VALID);
I think it's more common to write

```suggestion
		val->intval = !!(tmp & PM8916_LBC_USB_USBIN_VALID);
```

2020-10-30 12:30 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +	qcom,lbc-chgr-tchg-max = <0>;
I set hard limit as in downstream:
https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/cf1d8f550dad4f19d5d57eb2264bdc2205c857af/arch/arm/boot/dts/qcom/msm8916-qrd-l8150.dts#L158

Then I just allow lbc to regulate itself - it will draw as much as possible even when connected to "pc" (which means that if "pc" doesn't limit the current output - charger will happily pull more) Not sure if hardware can detect charger/data since usb lines seem to go straight into the SoC and I don't see anything useful in HRD for LBC.

2020-10-30 12:41 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +	qcom,lbc-chgr-tchg-max = <0>;
They do some very fancy cable detection in the USB PHY driver: https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/b20608408caff817ec874f325127b07609fbaeb8/drivers/usb/phy/phy-msm-usb.c#L1944-L1985

But it's rather complicated :|

2020-10-31 11:20 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +	qcom,ibat-safe = <810000>;
Did you reduce these recently? Downstream has slightly different values.

Also, should we set `VIN_MIN` as well?

2020-10-31 11:20 UTC, Minecrell commented on drivers/power/supply/pm8916_bms_vm.c
> +	};
```suggestion
	}
```

2020-10-31 11:20 UTC, Minecrell commented on drivers/power/supply/pm8916_bms_vm.c
> +			return -EPROBE_DEFER;
Does the driver really work properly without IRQ? Perhaps this should be

```c
irq = platform_get_irq(pdev, 0);
if (irq < 0)
	return irq;

ret = devm_request_threaded_irq(dev, irq, NULL
// ...
```

2020-10-31 11:20 UTC, Minecrell commented on drivers/power/supply/pm8916_lbc.c
> +	}
Perhaps the whole tchg-max code is pointless at the moment if you cannot handle CHG_FAILED?

2020-10-31 11:20 UTC, Minecrell commented on drivers/power/supply/pm8916_lbc.c
> +	}
same here as in vm-bms

2020-10-31 11:22 UTC, Minecrell commented on drivers/power/supply/pm8916_lbc.c
> +					 PM8916_LBC_CHGR_MAX_VOLTAGE, chg->charge_voltage_safe));
There are some Alignment should match open parenthesis here: https://cloud.drone.io/msm8916-mainline/linux/1133/1/3

Can you check that this is correctly indented with 8-width tabs?

2020-10-31 12:38 UTC, TravMurav commented on drivers/power/supply/pm8916_lbc.c
> +					 PM8916_LBC_CHGR_MAX_VOLTAGE, chg->charge_voltage_safe));
It should be aligned with `min_t(` but I didn't want to split it into three lines

2020-10-31 12:46 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +	qcom,ibat-safe = <810000>;
iirc they have .900 in dt but device never took more than .830 so I chose closest value from HRD. I can make it pull more (what I actually did while writing the driver but they probably chose this limit for a reason)

2020-10-31 12:52 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +	qcom,ibat-safe = <810000>;
Default 4.65v seems fine for `VIN_MIN`

2020-10-31 13:28 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +	qcom,ibat-safe = <810000>;
Hm but 900 is also a valid ibat-safe/max. Did your AC adapter not provide more or something?

Also, `vdd-safe` seems to be 4370 and vdd-max 4350, did you reduce that to 4300 on purpose?

2020-10-31 14:16 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +	qcom,ibat-safe = <810000>;
I use 2A adapter so it shouldn't be the problem. As of `vdd-safe` - Yes I intentionally reduced it a bit - there is "Limited charge voltage: 4.35v" written on the battery and I decided to be safe there. This shouldn't make a big difference imo

2020-10-31 14:20 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
> +	qcom,ibat-safe = <810000>;
OK for vdd-safe. As for ibat-safe, your driver seems to assume that LBC does "the right thing" in several other places so I would probably set it to 900 as on downstream.

2020-11-01 10:30 UTC, Minecrell commented on drivers/power/supply/Kconfig
> +          module will be called pm8916-bmS-vm.
```suggestion
          module will be called pm8916_bms_vm.
```

2020-11-01 10:30 UTC, Minecrell commented on drivers/power/supply/Kconfig
> +          module will be called pm8916-lbc-chgr.
```suggestion
          module will be called pm8916_lbc.
```

2020-11-01 10:30 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/pm8916.dtsi
> +			interrupts = <0x0 0x40 4 IRQ_TYPE_EDGE_BOTH>;
Is it really correct to use `IRQ_TYPE_EDGE_BOTH` here? Downstream seems to use `IRQF_TRIGGER_RISING` only for the fifo_update_done.

2020-11-02 07:26 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/pm8916.dtsi
> +			interrupts = <0x0 0x40 4 IRQ_TYPE_EDGE_BOTH>;
I think my thought process was like "Ok idk on which edge it will fire so I'll just add both and fix if it'll fire twice" but I guess controller somehow magically handles things and it just worked so I forgot to fix it. Changed to `RISING`

2020-11-02 08:09 UTC, Minecrell requested changes

2020-11-02 08:09 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/pm8916.dtsi
> +			interrupts = <0x0 0x13 1 IRQ_TYPE_EDGE_RISING>;
nonononoononono

```suggestion
			interrupts = <0x0 0x13 1 IRQ_TYPE_EDGE_BOTH>;
```

for usb-in we want to detect both "plugged in" and "plugged out"... :)

2020-11-02 08:39 UTC, merged