M216
msm8916-mainline/linux pull request #113
Opened 2020-10-08 15:58 UTC by cristianc

Add support for for LG K10 (K420n) - device tree

2020-10-08 20:54 UTC, Minecrell requested changes

2020-10-08 20:54 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-lg-m216.dts
> +&pm8916_resin {
I think you noticed that this is not working, so it should be removed.

2020-10-08 21:53 UTC, cristianc commented on arch/arm64/boot/dts/qcom/msm8916-lg-m216.dts
> +&pm8916_resin {
Fixed.

2020-10-09 09:15 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-lg-m216.dts
> +			compatible = "linux,extcon-usb-dummy";
```suggestion
		compatible = "linux,extcon-usb-dummy";
```

2020-10-09 15:02 UTC, Minecrell approved these changes

2020-10-09 15:04 UTC, merged