oppo-a51f: add sound support [WIP]
msm8916-mainline/linux pull request #125
Opened 2020-10-18 10:52 UTC by Hinokami-Kagura

2020-10-18 17:44 UTC, Minecrell requested changes

2020-10-18 17:44 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +			"Speaker Amp INR", "HPH_R_EXT",
This is mono speaker on HPH_L (bit weird I know)

```suggestion
			"Speaker Amp INR", "HPH_L_EXT",
```

2020-10-19 08:45 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +				"0",  "0", "1";
This looks like a weird change

2020-10-19 08:45 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	reg-names = "mic-iomux", "spkr-iomux";
compatible/reg/reg-names are unneeded

2020-10-19 08:45 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +		pinctrl-1 = <&cdc_pdm_lines_sus>;
indentation is broken here

2020-10-19 08:45 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	model = "wt88047";
```suggestion
	model = "oppo-a51f";
```

2020-10-19 08:45 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
>  	};
This change seems correct, but I need a separate commit for this so I can squash it into the commit that caused this.

2020-10-19 08:45 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	usb_id_sleep: usb-id-sleep {
This is unused?

2020-10-19 08:45 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +		enable-gpios = <&msmgpio 120 GPIO_ACTIVE_HIGH>;
Need pinctrl for this as well

2020-10-19 08:45 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	yda145_amp: yda145-amplifier {
The naming is rather confusing here, perhaps

```suggestion
	reg_speaker_boost: regulator-speaker-boost {
```

2020-10-19 08:56 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +				"0",  "0", "1";
because of TAB...

2020-10-19 08:58 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	model = "wt88047";
so if changed this, the UCM2 configuration need to matched?

2020-10-19 09:10 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +				"0",  "0", "1";
Yeah, but then it's not aligned anymore :)

2020-10-19 09:11 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	model = "wt88047";
Yes. I will create it for you.

2020-10-19 09:39 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +				"0",  "0", "1";
OK, Reverted it.

2020-10-19 09:39 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	reg-names = "mic-iomux", "spkr-iomux";
Thanks, I remove it.

2020-10-19 09:41 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	model = "wt88047";
OK, so I fixed that name defined, but does it need re-build the rootfs for checking?

2020-10-19 09:41 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
>  	};
Roger!

2020-10-19 09:41 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	usb_id_sleep: usb-id-sleep {
thanks, I forget to remove it.

2020-10-19 09:42 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +		enable-gpios = <&msmgpio 120 GPIO_ACTIVE_HIGH>;
so add a pinctrl for GPIO120 with same status as GPIO118, thanks!

2020-10-19 09:42 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	yda145_amp: yda145-amplifier {
OK, renamed related item.

2020-10-19 09:42 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	model = "wt88047";
Well, until I have created the UCM it won't work at all :D

2020-10-19 11:08 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	qcom,micbias1-ext-cap;
Jack detection is PASS, but sadly it can't use without the ts4621...

2020-10-19 11:45 UTC, Minecrell requested changes

2020-10-19 11:45 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
>  	};
You still have some odd re-ordering with speaker/touchscreen here. Maybe it's easier if you do the touchscreen changes in a separate PR...

2020-10-19 11:45 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	reg_speaker_boost_pin: regulator-speaker-boost-pin {
```suggestion
	speaker_boost_default: speaker-boost-default {
```

Would be a bit nicer for consistency.

2020-10-19 11:52 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
>  	};
OK, so I'll send another PR for this, thanks!

2020-10-19 12:38 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	speaker_boost_default: speaker-boost-default {
You are still reordering here, just look at the diff :/

2020-10-19 14:08 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +		output-low;
I don't really see a good reason for using bias-pull-down here, bias-disable + without output-low should be fine. Can you test?

2020-10-19 14:08 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	speaker_amp_default: speaker-amp-default {
speaker-amp should come before speaker-boost (alphabetically)

2020-10-19 14:08 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +		output-low;
bias-disable + remove output-low?

2020-10-19 14:34 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +		output-low;
only bias-disable, is ok (still I'm set the name as wt88047)

2020-10-19 14:34 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	speaker_amp_default: speaker-amp-default {
thanks, and changed!

2020-10-19 14:34 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +		output-low;
only bias-disable, is ok (still I'm set the name as wt88047)

2020-10-19 19:57 UTC, Minecrell approved these changes

2020-10-19 19:58 UTC, merged