Add panel driver for Ilitek ILI9881 which is needed for Lenovo A6010
msm8916-mainline/linux pull request #129
Opened 2020-10-25 20:11 UTC by jenneron

2020-10-26 12:45 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		remote-endpoint = <&panel_in>;
one tab here is enough

2020-10-26 12:45 UTC, Minecrell commented on drivers/gpu/drm/panel/panel-wingtech-yassy-ili9881.c
> +
You need to generate the panel driver with support for the two regulators (`--regulator vsp --regulator vsn`)

2020-10-26 12:45 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
Preferably we shouldn't keep these `regulator-always-on`. Sadly the situation with regulators like the TPS65132 is sometimes a bit difficult.

Theoretically, they have persistent configuration built-in, so modelling them as fixed-regulator should be sufficient. However, the persistent configuration does not necessarily need to be the correct one.

Alternatively, there is the https://github.com/torvalds/linux/blob/master/drivers/regulator/tps65132-regulator.c driver in mainline, but perhaps it does not do the correct configuration either.

I think I made a test driver at some point to check the configuration of the regulator after a power cycle, let me try to look it up.

2020-10-26 12:50 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
I found the driver:

https://gist.github.com/Minecrell/ff8fc736c0ab6caa659410e61cef161b

with configuration like

https://gist.github.com/Minecrell/e487120996e04f75m323f6942ed9cdeb4

Back then we we trying to figure out if nt50358 behaves like TPS65132 so it's effectively a driver for TPS65132. Basically it turns on/off the display every few seconds and dumps the register content. Can you try it?

2020-10-26 13:37 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
> with configuration like
> 
> https://gist.github.com/Minecrell/e487120996e04f75m323f6942ed9cdeb4
404

2020-10-26 13:59 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
https://gist.github.com/Minecrell/e487120996e04f75323f6942ed9cdeb4

2020-10-26 15:05 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
should i remove regulators before using it?

2020-10-26 15:54 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
Yes, they will probably conflict.

2020-10-26 17:58 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
it.. just works as it was before
wingtech-wt86528.dts - http://bpa.st/HWDA

2020-10-26 18:00 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
i haven't generated panel driver with regulators support yet if it is important

2020-10-26 18:06 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
You are supposed to look at the log when using it :D

2020-10-26 18:10 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
dmesg https://bpa.st/OFQQ

2020-10-26 18:18 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
Your TPS65132 seems to be connected to blsp_i2c2. Also you need to make blsp_i2c2 `status = "okay";`. Also make sure that you actually compiled the new driver :)

2020-10-26 18:29 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
the result is black screen with enabled backlight
dmesg http://bpa.st/CR3Q

2020-10-26 19:16 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
btw after removing regulator-always-on the result is black screen after 30 seconds

2020-10-26 21:13 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
seems it is fixed by generating panel driver with --regulator

2020-10-26 21:21 UTC, jenneron commented on drivers/gpu/drm/panel/panel-wingtech-yassy-ili9881.c
> +
done

2020-10-26 21:57 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
seems it is fixed by generating driver with --regulator. i removed regulator-always-on in recent push

2020-10-27 14:01 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
The log looks fine mostly but apparently active discharge is disabled (`APPS_DISP_DISN: 0x0`) even though downstream has `ti,discharge-enable;`. Can you perhaps try using the mainline `TPS65132` driver? Make sure you set the correct voltages.

Here is the binding documentation: https://github.com/torvalds/linux/blob/master/Documentation/devicetree/bindings/regulator/tps65132-regulator.txt

2020-10-27 14:19 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
doesn't work with this dts http://bpa.st/GZBQ
dmesg http://bpa.st/7EQA

2020-10-27 14:24 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
that is caused trying to use tps65132 driver with dts above :/
https://i.imgur.com/cSQmwY8.png

2020-10-27 14:26 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
I assume it's not permanent? :D

2020-10-27 14:26 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
i hope

2020-10-27 14:29 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
yep it almost disappeared

2020-10-27 14:31 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
It's not entirely clear to me if the driver was actually loaded. Did you enable it in the kernel config?

2020-10-27 14:34 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
oops i didn't

2020-10-27 14:37 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
works

2020-10-27 14:41 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
as far as i understand i need to update dts with this driver. should it be enabled as built-in?

2020-10-27 14:48 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
> should it be enabled as built-in?

Yes, probably. Since it's needed for the display.

Can you try with `regulator-active-discharge = <1>;` on both positive and negative? I believe that should be equivalent to `regulator-active-discharge = <0>;`.

Also remove `regulator-boot-on;` and `enable-active-high`, that should not be needed for the real driver.

2020-10-27 15:26 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
result is the same with `regulator-active-discharge = <1>;` and with `regulator-active-discharge = <0>;` and without it. what i should keep?

2020-10-27 15:59 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
Hmm. Well, without `regulator-active-discharge = <1>;` we could just use it as fixed-regulator, which would be easier. I don't really know if the active discharge feature is meaningful in any way. Does it look any different when turning the display off?

2020-10-27 16:07 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
seems it doesn't. i don't know what difference it should be

2020-10-27 16:28 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		regulator-always-on;
Meh, well I guess I'm slightly in favor of the `fixed-regulator` approach then. Will resolve this conversation, thanks for testing!

2020-10-27 17:08 UTC, Minecrell requested changes

2020-10-27 17:08 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		enable-active-high;
let's add `startup-delay-us = <800>` here for consistency with `ti,enable-time = <800>;`

2020-10-27 17:08 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		enable-active-high;
(same for neg)

2020-10-27 17:25 UTC, jenneron commented on arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
> +		enable-active-high;
done

2020-10-27 17:38 UTC, Minecrell approved these changes

2020-10-27 17:39 UTC, merged