arm64: dts: qcom: msm8916-motorola-osprey: add panel driver
msm8916-mainline/linux pull request #134
Opened 2020-10-30 15:58 UTC by MartijnBraam

Panel driver generated using the msm8916 panel generators. The
regulators aren't working yet but it seems to work mostly without them.

2020-10-30 16:49 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +		compatible = "inx,500-v0";
Can you build https://github.com/msm8916-mainline/lk2nd/pull/41 (if that's complicated for some reason I can also provide a `lk2nd.img`, just ping me on Matrix) and change this to

```suggestion
		compatible = "motorola,osprey-panel";
```

Then, change the compatible in the panel driver to `motorola,osprey-panel-inx`, and please also name the driver file like that, i.e. `panel-motorola-osprey-inx.c` and CONFIG_DRM_PANEL_MOTOROLA_OSPREY_INX.

The idea is that lk2nd will replace the `"motorola,osprey-panel"` with `"motorola,osprey-panel-inx"` and therefore ensure that the correct panel driver is used. Osprey can have one of multiple panels.

Also, please make a separate commit for the driver (`drm/panel: ...`) and for the dts part (`arm64: dts: ...`).

2020-10-30 16:49 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +			pins = "gpio25";
You probably want `gpio78` here, since it refers to the reset gpio :)

2020-10-30 16:49 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +		backlight-gpios = <&msmgpio 36 GPIO_ACTIVE_HIGH>;
We should represent this as fixed regulator by adding another vddio-supply to the panel driver, like on downstream: https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/acb58b87ca778866b44f791a80adc62af111e0f4/arch/arm/boot/dts/qcom/msm8916-osprey.dtsi#L252-L259 

(Actually, https://www.onsemi.com/pub/Collateral/FPF1504-D.PDF suggests this isn't really a fixed regulator but whatever...)

2020-10-30 16:49 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +				enable-gpios = <&pm8916_gpios 3 0>;
1. for both outp/outn:

    ```suggestion
    				enable-gpios = <&pm8916_gpios 3 GPIO_ACTIVE_HIGH>;
    ```

2. and we should add pinctrl for both. Note that this looks a bit different in downstream and mainline than normal pinctrl:

    https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/acb58b87ca778866b44f791a80adc62af111e0f4/arch/arm/boot/dts/qcom/msm8916-osprey.dtsi#L218-L236

    You probably want something like:

    ```
    &pm8916_gpios {
    	disp_en_default: disp-en-default {
    		pins = "gpio3", "gpio4";
    		function = PMIC_GPIO_FUNC_NORMAL; // qcom,src-sel = <0>
    
    		bias-disable; // qcom,pull = <5>
    		power-source = <PM8916_GPIO_L2>; // qcom,vin-sel = <2>?
    	};
    };
    ```

3. also afaik `ti,discharge-enable` translates to `regulator-active-discharge = <1>;` on both outp/outn.

2020-10-30 16:49 UTC, Minecrell commented on drivers/gpu/drm/panel/panel-inx-500-v0.c
> +	//	return dev_err_probe(dev, ret, "Failed to get regulators\n");
I would prefer not merging it with these hacks :) Can we spend a little more time to set it up properly?

2020-10-31 13:35 UTC, MartijnBraam commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +		backlight-gpios = <&msmgpio 36 GPIO_ACTIVE_HIGH>;
I think this is neither a regulator or a vddio supply

2020-10-31 13:37 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +		backlight-gpios = <&msmgpio 36 GPIO_ACTIVE_HIGH>;
It says "DISPLAY/TOUCH DIGITAL SUPPLY" in the schematics. I would argue it's more a regulator than a backlight GPIO. :P

2020-10-31 13:46 UTC, MartijnBraam commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +		backlight-gpios = <&msmgpio 36 GPIO_ACTIVE_HIGH>;
I see, why is it marked as backlight... seems like the panel controls it's own backlight regulator

2020-10-31 13:47 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +		backlight-gpios = <&msmgpio 36 GPIO_ACTIVE_HIGH>;
Well, where did the "backlight" even come from? I don't see how it is related to backlight.

2020-10-31 14:28 UTC, Minecrell requested changes

2020-10-31 14:28 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +		gpio = <&msmgpio 36 GPIO_ACTIVE_HIGH>;
For consistency we should add pinctrl for this. Something like

```
	panel_vddio_default: panel-vddio-default {
		pins = "gpio36";
		function = "gpio";

		drive-strength = <2>;
		bias-disable;
	};
```

2020-10-31 14:28 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +			pins = "gpio25";
I would change something on this line :)

2020-10-31 14:28 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +		power-source = <PM8916_GPIO_L2>; // qcom,vin-sel = <2>;
The comments were only for explanation, please remove them :D

2020-10-31 14:28 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +		reg = <0x3e>;
You actually need to reference the `disp_en_default` pinctrl here :)

2020-10-31 14:28 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +&blsp_i2c1 {
Please move this above `&dsi0`, the order should be like explained in https://wiki.postmarketos.org/wiki/MSM8916_Mainlining#Device_Tree_Structure

2020-10-31 14:28 UTC, Minecrell commented on drivers/gpu/drm/panel/panel-motorola-osprey-inx.c
> +	{ .compatible = "motorola,osprey-panel-inx" }, // FIXME
```suggestion
	{ .compatible = "motorola,osprey-panel-inx" },
```

2020-10-31 14:28 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +	vddio_panel_reg: vddio_panel_reg {
```suggestion
	reg_panel_vddio: regulator-panel-vddio {
```

^ this would look more consistent with `reg_lcd_pos/reg_lcd_neg`

2020-10-31 14:52 UTC, MartijnBraam commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +			pins = "gpio25";
?

2020-10-31 15:05 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +			pins = "gpio25";
Compare the GPIO with  mdss-active perhaps :)

2020-10-31 15:11 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> -/* CTS/RTX are not used */
This was correct here since it belongs to pinctrl :/

```
<stuff>
<regulators>
<pinctrl>
```

2020-10-31 15:11 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +		// I HEREBY REFERENCE THE disp_en_default PINCTRL
```suggestion
		pinctrl-names = "default";
		pinctrl-0 = <&disp_en_default>;
```

2020-10-31 15:11 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-motorola-osprey.dts
> +		gpio = <&msmgpio 36 GPIO_ACTIVE_HIGH>;
\+

```
		pinctrl-names = "default";
		pinctrl-0 = <&panel_vddio_default>;
```

2020-10-31 15:35 UTC, Minecrell approved these changes

2020-10-31 15:54 UTC, merged