samsung-j5nlte: add accelerometer
msm8916-mainline/linux pull request #136
Opened 2020-10-31 18:50 UTC by nergzd723

2020-10-31 18:54 UTC, Minecrell requested changes

2020-10-31 18:54 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5nlte.dts
> +			pinctrl-0 = <&accel_int_default>;
pinctrl-0 always needs to be paired with pinctrl-names

2020-10-31 18:54 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5nlte.dts
> +		pinctrl-names = "default";
pinctrl-names always needs to be paired with pinctrl-0

2020-10-31 18:54 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5nlte.dts
> +	accel_int_default: accel_int_default {
```suggestion
	accel_int_default: accel-int-default {
```

2020-10-31 18:54 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5nlte.dts
> +	sensors_i2c2: sensors_i2c2 {
You can combine this to one pinctrl,

```
pins = "gpio31", "gpio32";
```

2020-10-31 18:54 UTC, Minecrell commented
Also, please check sensor according to https://wiki.postmarketos.org/wiki/MSM8916_Mainlining#Testing_2

2020-10-31 19:16 UTC, nergzd723 commented
> Also, please check sensor according to https://wiki.postmarketos.org/wiki/MSM8916_Mainlining#Testing_2

it works:

```
    Accelerometer orientation changed: right-up
    Accelerometer orientation changed: normal
    Accelerometer orientation changed: right-up
    Accelerometer orientation changed: bottom-up
    Accelerometer orientation changed: right-up
    Accelerometer orientation changed: left-up
    Accelerometer orientation changed: normal

```

2020-10-31 19:19 UTC, Minecrell requested changes

2020-10-31 19:19 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5nlte.dts
> +	sensors_i2c: sensors_i2c {
```suggestion
	sensors_i2c_default: sensors-i2c-default {
```

2020-10-31 19:26 UTC, Minecrell requested changes

2020-10-31 19:26 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5nlte.dts
> +		pinctrl-0 = <&accel_int_default>;
this one should have the i2c pinctrl, while the accel pinctrl should be on the accel node, obviously :)

2020-11-01 10:14 UTC, Minecrell requested changes

2020-11-01 10:14 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5nlte.dts
> +	};
pinctrl should be sorted alphabetically ^-^

2020-11-02 08:22 UTC, Minecrell commented
I fixed the rest up for you, but please order pinctrl alphabetically next time :)

2020-11-02 08:33 UTC, Minecrell approved these changes

2020-11-02 08:42 UTC, merged

2020-11-02 08:52 UTC, nergzd723 commented
> I fixed the rest up for you, but please order pinctrl alphabetically next time :)

Thanks :)