Asus Zenfone 2 Laser (720p): Add Display,Backlight and Touchscreen support.
msm8916-mainline/linux pull request #138
Opened 2020-11-11 17:49 UTC by antony-jr

This PR adds support for display panel, backlight and touchscreen for Asus Zenfone 2 (720p) (Codename: asus-z00l).

2020-11-11 17:56 UTC, antony-jr commented
Oops too many style errors. Please review only the logic, I will take care of the style.

2020-11-12 09:49 UTC, Minecrell requested changes

2020-11-12 10:55 UTC, antony-jr commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +                compatible = "mdss,otm1284a";
So should I write a documentation in ```Documentation/devicetree/...``` too? like how asus-z00t does? FYI asus-z00t is already in mainline kernel. But only the dts file is missing.

2020-11-12 11:10 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +                compatible = "mdss,otm1284a";
You don't need to write device tree documentation for merge in this repository, but you would need to write it when upstreaming your patches.

2020-11-12 15:04 UTC, antony-jr commented on drivers/gpu/drm/panel/panel-asus-z00l-otm1284a.c
> +static int otm1284a_bl_get_brightness(struct backlight_device *bl)
Yes there was. I thought actual_brightness gave the right value but it only gives -61 all the time so I removed the function.

2020-11-12 15:13 UTC, antony-jr commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +		backlight-gpios = <&msmgpio 21 GPIO_ACTIVE_LOW>;
I have to make note here, Removing this line(```backlight-gpios```) has no effect. But it is in downstream.

2020-11-12 15:13 UTC, antony-jr commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +		pinctrl-0 = <&lcd_bl_en_default>;
This line also has no effect.

2020-11-12 15:42 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +		pinctrl-0 = <&lcd_bl_en_default>;
pinctrl-0 needs to be paired with pinctrl-names to have effect.

2020-11-12 15:42 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +		backlight-gpios = <&msmgpio 21 GPIO_ACTIVE_LOW>;
You need to generate your panel driver with `--backlight-gpio` to make use of this.

2020-11-12 15:55 UTC, antony-jr commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +		pinctrl-0 = <&lcd_bl_en_default>;
Let me try with that.

2020-11-12 16:47 UTC, antony-jr commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +		backlight-gpios = <&msmgpio 21 GPIO_ACTIVE_LOW>;
Okay I used the driver with --backlight-gpio and set backlight-gpios, Then the display stopped working. But this time when I press the power key I can see the Phosh lockscreen for a second and it turns off. So I think this needs to be avoided.

2020-11-12 17:52 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +		backlight-gpios = <&msmgpio 21 GPIO_ACTIVE_LOW>;
Have you tried GPIO_ACTIVE_HIGH for the backlight?

2020-11-12 20:08 UTC, antony-jr commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +		backlight-gpios = <&msmgpio 21 GPIO_ACTIVE_LOW>;
Yep. GPIO_ACTIVE_HIGH fixed it.

2020-11-12 20:10 UTC, antony-jr commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +		pinctrl-0 = <&lcd_bl_en_default>;
Okay I've given ```pinctrl-names = "default"``` but no effect from this, The display is working fine. I'm just curious what this adds to the kernel? I still see the glitch when changing brightness but it is stable when using it display.

2020-11-13 18:58 UTC, antony-jr commented
@Minecrell Anything else that needs to be changed?

2020-11-14 14:06 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +                compatible = "mdss,otm1284a";
You didn't implement it like I suggested, you should put `asus,z00l-panel` here and let lk2nd replace it with `asus,z00l-otm1284a` after detecting your panel :)

2020-11-14 14:44 UTC, Minecrell commented
See above.

Also, I think we should generate the panel driver with a power supply/regulator (`--regulator power`).

Downstream source suggests this should be `pm8916_l8`: https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/1a445c1767d9a60f4cce9fca61c9e4c84e2b44c3/arch/arm/boot/dts/qcom/msm8916-mdss.dtsi#L123

i.e. `power-supply = <&pm8916_l8>`.

2020-11-14 15:11 UTC, antony-jr commented
> See above.
> 
> Also, I think we should generate the panel driver with a power supply/regulator (`--regulator power`).
> 
> Downstream source suggests this should be `pm8916_l8`: https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/1a445c1767d9a60f4cce9fca61c9e4c84e2b44c3/arch/arm/boot/dts/qcom/msm8916-mdss.dtsi#L123
> 
> i.e. `power-supply = <&pm8916_l8>`.

Thanks for the review. I will look into this ASAP.

2020-11-14 20:49 UTC, antony-jr commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +                compatible = "mdss,otm1284a";
After using asus,z00l-panel in the dts file. Now the display does not work. I can note that the panel section in lk2nd is showing ```qcom,mdss_dsi_otm1284a_720p_video```.

2020-11-15 10:52 UTC, antony-jr commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +                compatible = "mdss,otm1284a";
@Minecrell it fails to register the DSI host -> ```msm_dsi_manager_register: failed to register mipi dsi host 
for DSI 0``` when using ```asus,z00l-panel```

2020-11-16 11:21 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +                compatible = "mdss,otm1284a";
Did you build + install the new lk2nd? https://github.com/msm8916-mainline/lk2nd/pull/41

2020-11-16 11:35 UTC, antony-jr commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +                compatible = "mdss,otm1284a";
I did build from the master branch just yesterday and installed the new one. I will try using the panel-selection branch and report back. Thanks for your time.

2020-11-16 13:12 UTC, antony-jr commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +                compatible = "mdss,otm1284a";
I can confirm this works with using lk2nd/panel-selection branch.

2020-11-16 14:03 UTC, antony-jr commented
> See above.
> 
> Also, I think we should generate the panel driver with a power supply/regulator (`--regulator power`).
> 
> Downstream source suggests this should be `pm8916_l8`: https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/1a445c1767d9a60f4cce9fca61c9e4c84e2b44c3/arch/arm/boot/dts/qcom/msm8916-mdss.dtsi#L123
> 
> i.e. `power-supply = <&pm8916_l8>`.

Okay I've done the requested changes. Also generated the driver with power supply and given ```power-supply = <&pm8916_l8>;```.

2020-11-16 15:50 UTC, Minecrell commented
Changes look good, but can you make a separate commit for panel driver and the dts part? i.e.

- `drm/panel: ...`
- `arm64: dts: qcom: ...`

Since those will be applied separately later if you decide to upstream them.

Personally I would prefer if touchscreen was also a separate commit, but this isn't strictly required.

2020-11-16 16:32 UTC, antony-jr commented
> Changes look good, but can you make a separate commit for panel driver and the dts part? i.e.
> 
>     * `drm/panel: ...`
> 
>     * `arm64: dts: qcom: ...`
> 
> 
> Since those will be applied separately later if you decide to upstream them.
> 
> Personally I would prefer if touchscreen was also a separate commit, but this isn't strictly required.

Okay. I will do this in a moment.

2020-11-16 17:42 UTC, antony-jr commented
Okay made changes in separate commits.

2020-11-16 18:32 UTC, Minecrell requested changes

2020-11-16 18:32 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +		pins = "gpio97";
I'm really sorry that I keep finding things... Why is this `gpio97` rather than gpio21? :)

2020-11-16 18:52 UTC, antony-jr commented on arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
> +		pins = "gpio97";
I think I made a mistake here. I read a comment. https://github.com/LineageOS/android_kernel_asus_msm8916/blob/1a45c63742b8c3253a38c2ff97b672918c88d8df/arch/arm/boot/dts/qcom/msm8916-mtp-ze550kl.dtsi#L491

Reviews are always welcomed.

2020-11-17 12:05 UTC, Minecrell approved these changes

2020-11-17 12:49 UTC, Minecrell commented
Pushed, thanks :)

2020-11-17 12:49 UTC, closed without merging