Add gt58lte to device tree (reuse common dts for gt5)
msm8916-mainline/linux pull request #195
Opened 2021-05-09 17:43 UTC by hello-world-321

2021-05-09 18:24 UTC, TravMurav requested changes
Please also look at checkpatch warnings/errors in CI, you should fix at least some that are related to e.g. newlines
You should also add signoff for squash! to make checkpatch happy

2021-05-09 18:24 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt58.dts
> +	reg_vdd_tsp: regulator-vdd-tsp {
For: *gt58 uses Zinitix bt532 touch controller.*
Please reword this commit description in line with other commits in the Linux tree

See https://www.kernel.org/doc/html/v4.10/process/submitting-patches.html#describe-your-changes

Add file prefixes,
> Describe your changes in imperative mood, e.g. “make xyzzy do frotz” instead of “[This patch] makes xyzzy do frotz” or “[I] changed xyzzy to do frotz”, as if you are giving orders to the codebase to change its behaviour.

2021-05-09 18:24 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt58.dts
> +	tsp_rst_default: tsp-rst-default {
This pinctrl is unused and thus isn't executed, move this gpio into `tsp-int-default` and maybe rename to e.g. `tsp-rst-int-default`

2021-05-09 18:24 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt5-common.dtsi
> +		pinctrl-0 = <&accel_int_default>;
pinctrl is usually at the end of the node for devices like this

2021-05-09 18:24 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt5-common.dtsi
> +		reg = <0x1d>;
Please put reg the first after compatible

2021-05-09 18:24 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt5-common.dtsi
> +&blsp_i2c2 {
For *arm64: dts: qcom: msm8916-samsung-gt5-common: Sensors: Accelerometer,…*
Also reword the commit name

2021-05-09 18:24 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt58.dts
> +	i2c-amplifier {
For: *arm64: dts: qcom: msm8916-samsung-gt58: Add sound card*
Wrap commit description at 75 columns (https://www.kernel.org/doc/html/v4.10/process/submitting-patches.html#the-canonical-patch-format)

2021-05-09 18:24 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt58lte-modem.dts
> +	model = "Samsung Galaxy Tab A 8.0 LTE (2015) (SM-T355Y)";
Probably just `(SM-T355)` for all the variants?

2021-05-09 18:24 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt58lte-modem.dts
> +	compatible = "samsung,gt58lte", "samsung.gt58", "qcom,msm8916";
`"samsung.gt58"` should have comma, not dot

2021-05-09 18:24 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt58.dts
> +	vibrator_en_default: vibrator-en-default {
Need to add pinctrl to the vibrator node

2021-05-10 10:02 UTC, TravMurav requested changes
Some changes are mixed up between commits now, specifically

* arm64: dts: qcom: msm8916-samsung-gt58: Add display panel
* arm64: dts: qcom: msm8916-samsung-gt58: Add Vibrator

have their changes in other commits.

I recommend opening "commits" tab and looking through after you pushed a branch to spot things like this.

2021-05-10 12:55 UTC, TravMurav requested changes
Now the commit that adds the panel was lost completely :/

While fixing that, please reorder the commits like:

- squash! MSM8916: arm64: configs: Add msm8916_defconfig (v38)
- drivers: iio: light: cm3323: Add device tree support
- arm64: dts: qcom: msm8916-samsung-gt5-common: add sensors
- arm64: dts: qcom: Add device tree for Samsung Galaxy Tab A 8.0 (2015)
- arm64: dts: qcom: msm8916-samsung-gt58: Add Vibrator
- arm64: dts: qcom: msm8916-samsung-gt58: Add touchscreen
- *arm64: dts: qcom: msm8916-samsung-gt58: Add display*
- arm64: dts: qcom: msm8916-samsung-gt58: Add sound card
- arm64: dts: qcom: Add modem for gt58lte

The reason for that is that first 6 of those don't depend on stuff like sound/display/modem which we didn't yet decided how to handle in upstream. Ordering those in order of "completeness" should make maintaining and upstreaming this easier

Also the mount matrix still seems to be a bit misaligned

2021-05-10 14:59 UTC, TravMurav requested changes

2021-05-10 14:59 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt58.dts
> +	tsp_en_default: tsp-en-default {
Please correct the name of this pinctrl to reflect that it belongs to a regulator and not the touchscreen (e.g. `reg-tsp-en-default`)

2021-05-10 14:59 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt58.dts
> +	lcd_en_default: lcd-en-default {
reg-lcd-...

2021-05-11 11:00 UTC, Minecrell commented on drivers/iio/light/cm3323.c
> +	{}
A common practice recently is to do

```c
{ /* sentinel */ }
```

for the last element of such lists.

2021-05-11 11:00 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt5-common.dtsi
> +		vdd-supply = <&pm8916_l17>;
The cm3323 driver does not seem to have regulator support at the moment, you would need to add it to make it use of this.

2021-05-11 11:00 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt58.dts
> +		reset-gpios = <&msmgpio 114 GPIO_ACTIVE_LOW>;
Are you sure gpio114 has anything to do with reset-gpios? According to schematics + downstream, gpio114 is "TSP_VENDOR1" (whatever that means, it does not seem to be used). The reset pin of BT532 is hardwired to `TSP_VDD_2.8V` (i.e. TSP_EN/gpio73).

Actually, it doesn't look like the zinitix driver even supports/uses reset-gpios so I'd suggest that you just remove this line.

2021-05-11 11:00 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt58.dts
> +		zinitix,mode = <2>;
iirc that's the default, so does not need to be specified

2021-05-11 11:00 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt58.dts
> +		pinctrl-0 = <&buckbooster_en_default>;
According to schematics, the buckbooster (5p4v) is enabled by gpio8 on SM-T355.

GPIO51 does not really seem to go anywhere useful, or at least it's not used to enable a regulator (`BACKLIGHT_PWM_AP`).

2021-05-11 11:00 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gt58.dts
> +		vmipi-supply = <&reg_vmipi>;
while `VMIPI_1.8V_AP` is actually provided by `&pm8916_l5`.

2021-07-13 19:08 UTC, TravMurav requested changes
Hi, I've rebased gt5 branches on top of latest master and did a bit of cleanup. I also took some of your commits so initial patches make more sense (I've squashed initial dt for gt58 and gt510 into one patch). Can you please rebase your commits on top of the new branch and drop ones that I already took. afaict you should only have 4 left. Also check that the entire branch still make sense for you (maybe you will have some comments?) then you should boot test the entire thing.

I believe that at this point this is mostly done and we can start sending some patches upstream :) I'm planning to send the fuel-gauge compatible as well as initial dts for both gt5 devices. I will expect you to send bindings and dt support for the light sensor as well as the rest of your patches (that can be upstreamed) after first ones are applied.

It seems like you didn't check matrix recently. If you don't have time to finish this, please tell me and I'll see what I can do here myself. 

Sorry that all of this takes so much time

2021-07-27 16:18 UTC, TravMurav requested changes

2021-07-27 16:18 UTC, TravMurav commented on Documentation/devicetree/bindings/trivial-devices.yaml
> +            # CM3323: Ambient Light Sensor
Looks like there it's 
```
  # comment
- name
```
as I'm pretty sure dallas is the "High-Precision Digital Thermometer" :)

2021-07-28 16:35 UTC, TravMurav approved these changes

2021-07-28 16:38 UTC, merged