arm64: dts: qcom: msm8916-samsung-j5xlte-eur: Add initial dts for j5xlte-eur
msm8916-mainline/linux pull request #196
Opened 2021-06-02 12:15 UTC by Exkinom

What works:
USB
eMMC
SD card
gpio-keys

Notes:
Using https://wiki.postmarketos.org/wiki/MSM8916_Mainlining#Otherwise for USB, as there isn't any sm5703 MUIC in mainline (yet).
Also unsure if the reserved-memory node is needed, almost all the other samsung devices has this. Any ideas?

2021-06-02 18:45 UTC, Minecrell commented
The reserved-memory node is based on this

https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/a516b4516645bace35af1bfb2d1ab3d398f929cb/arch/arm/boot/dts/samsung/msm8916/msm8916-memory.dtsi#L20-L30

So yes, you should add it.

Can you please read the [contribution guidelines](https://github.com/msm8916-mainline/linux/blob/master/CONTRIBUTING.md), especially the part about the `Signed-off-by`? I'm afraid I cannot accept patches without that. Let me know if you have any questions.

Also, I think it has turned out to be overkill to use the -eur suffix for devices, so please just name your dts `msm8916-samsung-j5xlte.dts`. Thanks.

2021-06-03 07:55 UTC, JosefWMenad commented
It seems like the build failed, did I put the Signed-off-by line in the wrong place? Thank you for your help.

2021-06-03 08:01 UTC, Minecrell commented
The first commit is still missing the `Signed-off-by:`. You need to squash them and make sure they use the correct author.

One way would be to "soft reset" the commits (note the `--soft` so you don't undo your changes but only the commits):

```
git reset --soft HEAD~2
```

And then just make a new, proper commit with all the changes:

```
git commit -s
```

And then force push:

```
git push --force
```

2021-06-03 08:13 UTC, JosefWMenad commented
I think I have it now. Thanks for the fast response:)

2021-06-03 09:46 UTC, Minecrell requested changes

2021-06-03 09:46 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5xlte.dts
> +	model = "Samsung Galaxy J5 2016 LTE (EUR)";
```suggestion
	model = "Samsung Galaxy J5 2016 LTE";
```

2021-06-03 20:25 UTC, Minecrell commented
I don't see any change yet :O

2021-06-04 09:36 UTC, Minecrell approved these changes

2021-06-04 09:39 UTC, Minecrell commented
Pushed, after squashing. Thanks!

2021-06-04 09:39 UTC, closed without merging