arm64: dts: msm8916-alcatel-idol347: dd initial devicetree
msm8916-mainline/linux pull request #207
Opened 2021-11-13 13:19 UTC by wonderfulShrineMaidenOfParadise

2021-11-14 05:36 UTC, TravMurav reviewed
There is too many "HACK IDK" all around.

I'd appreciate if there were a bit more descriptions on the commits.

Also please reorder commits akin to other devices, e.g. like this:
https://github.com/msm8916-mainline/linux/commits/master/arch/arm64/boot/dts/qcom/msm8916-longcheer-l8910.dts

2021-11-14 05:36 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		/*HACK IDK */
All of this looks very wrong to me...

2021-11-14 05:36 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		/*NOTE For J320P and J320R4 use i2c3 */
I'm starting to wonder if this device deserves a more specific name

2021-11-14 05:36 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +	tkey_en_default: tkey-en-default {
If this is for a regulator, name should probably reflect that

2021-11-14 12:36 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +	tkey_en_default: tkey-en-default {
How should we name it? Something like `tkey_i2c_default`?

2021-11-14 12:44 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		/*HACK IDK */
What I don't actually know is the voltage. I tried `1800000` and `3000000`. The panel is powered up but I have no idea about the difference.

2021-11-14 14:06 UTC, wonderfulShrineMaidenOfParadise commented
Reordered and added some descriptions from the templates.

2021-11-14 14:27 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +	tkey_en_default: tkey-en-default {
I copied it from `https://github.com/msm8916-mainline/linux/blob/master/arch/arm64/boot/dts/qcom/msm8916-samsung-serranove.dts#L581`. Is there a naming standard for this?

2021-11-15 05:28 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		/*HACK IDK */
well, there is actually no difference (the regulator is "fixed") but for the sake of correctness we want the voltage to be defined as it is in reality. If you know from some information source that it should be 3v - then you write 3v there (I'm pretty sure this is not 1v8)

2021-11-15 05:29 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +	tkey_en_default: tkey-en-default {
I suppose that one was called by the line name in the device schematics. This is also acceptable if you can confirm it.

2021-11-15 05:33 UTC, TravMurav reviewed
> This dts adds support **for wifi** and lte variants of
> Samsung Galaxy J3 smartphone released in 2016.

Please show me one, I want to see it :P

P.S. Other than that the commit order and messages look fine.
Comments about all the "HACK/TODO" still stand

2021-11-15 06:22 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +	tkey_en_default: tkey-en-default {
Maybe `touch_key_en` like the schematics?

2021-11-16 05:43 UTC, JulianGro commented
> Please show me one, I want to see it :P

Gotta get a photo with a fumo holding it :+1:

2021-11-16 10:40 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		vdd-supply = <&pm8916_l17>;
Could be the most of quirky part in this commit...

2021-11-16 10:44 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		touchkey: touchkey@20 {
Not actually working. To be checked.

2021-11-16 11:23 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		touchkey: touchkey@20 {
## evtest

```
samsung-j3:~$ evtest
No device specified, trying to scan all of /dev/input/event*
Not running as root, no devices may be available.
Available devices:
/dev/input/event0:      pm8941_pwrkey
/dev/input/event1:      pm8941_resin
/dev/input/event2:      GPIO Buttons
/dev/input/event3:      tm2-touchkey
/dev/input/event4:      msm8916 Headset Jack
Select the device event number [0-4]: 3
Input driver version is 1.0.1
Input device ID: bus 0x18 vendor 0x0 product 0x0 version 0x0
Input device name: "tm2-touchkey"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 158 (KEY_BACK)
    Event code 580 (KEY_APPSELECT)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)
Event: time 1637061515.722608, type 4 (EV_MSC), code 4 (MSC_SCAN), value 00
Event: time 1637061515.722608, type 1 (EV_KEY), code 580 (KEY_APPSELECT), value 1
Event: time 1637061515.722608, -------------- SYN_REPORT ------------
Event: time 1637061516.129422, type 4 (EV_MSC), code 4 (MSC_SCAN), value 00
Event: time 1637061516.129422, -------------- SYN_REPORT ------------
Event: time 1637061519.102858, type 4 (EV_MSC), code 4 (MSC_SCAN), value 00
Event: time 1637061519.102858, -------------- SYN_REPORT ------------
Event: time 1637061519.384436, type 4 (EV_MSC), code 4 (MSC_SCAN), value 00
Event: time 1637061519.384436, -------------- SYN_REPORT ------------
Event: time 1637061519.934678, type 4 (EV_MSC), code 4 (MSC_SCAN), value 01
Event: time 1637061519.934678, type 1 (EV_KEY), code 158 (KEY_BACK), value 1
Event: time 1637061519.934678, -------------- SYN_REPORT ------------
Event: time 1637061520.499556, type 4 (EV_MSC), code 4 (MSC_SCAN), value 01
Event: time 1637061520.499556, -------------- SYN_REPORT ------------
Event: time 1637061520.712593, type 4 (EV_MSC), code 4 (MSC_SCAN), value 01
Event: time 1637061520.712593, -------------- SYN_REPORT ------------
Event: time 1637061520.943507, type 4 (EV_MSC), code 4 (MSC_SCAN), value 01
Event: time 1637061520.943507, -------------- SYN_REPORT ------------
```

## dmesg

```
[   22.125013] input: tm2-touchkey as /devices/platform/i2c-tkey/i2c-1/1-0020/input/input3
[   68.581548] tm2-touchkey 1-0020: invalid keycode index -1
[   68.967096] tm2-touchkey 1-0020: invalid keycode index -1
[   71.972846] tm2-touchkey 1-0020: invalid keycode index -1
[   72.236161] tm2-touchkey 1-0020: invalid keycode index -1
[   72.772345] tm2-touchkey 1-0020: invalid keycode index -1
[   73.333691] tm2-touchkey 1-0020: invalid keycode index -1
[   73.542994] tm2-touchkey 1-0020: invalid keycode index -1
[   73.784719] tm2-touchkey 1-0020: invalid keycode index -1
```

2021-12-14 07:59 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		vdd-supply = <&pm8916_l17>;
Dropped this quirk and `panel-simple`. I generated  `panel-samsung-s6e8aa5x01-ams497hy01`, which doesn't need this. But it will be duplicated with the entry in `panel-simple`. It could be submitted in another pull request for more discussions.

2021-12-14 08:56 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		"AMIC3", "MIC BIAS External1";
`Secondary Microphone - msm8916` doesn't work.

2021-12-23 02:25 UTC, wonderfulShrineMaidenOfParadise commented
The panel is fixed to fit schematics, but with a hack. Instead of GPIO 102 `lcd_ldo_en`, using GPIO 16 `tsp_ldo_en`, which is less likely to be used, to power it up.

2021-12-23 02:26 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		gpio = <&msmgpio 16 GPIO_ACTIVE_HIGH>;
The panel is fixed to fit schematics, but with a hack. Instead of GPIO 102 `lcd_ldo_en`, using GPIO 16 `tsp_ldo_en`, which is less likely to be used, to power it up.

2021-12-23 02:29 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +			       "0", "0", "-1";
It's somehow not so accurate, and fixing it may require calculation.

2022-01-01 07:17 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		/* NOTE For J320N0 and J320ZN, use
Can you add an ["Union"](https://en.wikipedia.org/wiki/Union_(set_theory)) of those regions so the same reserved memory works for both variants?

2022-01-01 07:17 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +			lable = "Home Key";
Typo, copied from j5 I suppose :)

2022-01-01 07:17 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		/* NOTE It should be GPIO 102 (LCD_LDO_EN) but somehow the panel
if you have a no-op regulator, maybe drop it completely, the kernel will give it a dummy regulator with the same effect. Did you check that controlling that regulator really break things? Maybe the signal is just inverted? (e.g. active low and you were disabling the regulator instead of enabling it?)

2022-01-01 07:17 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		/* NOTE For J320N0 and J320ZN, use
same: try picking the bigger one so both can fit. (and gps_mem can be in any place as long as the size is correct.)

2022-02-07 16:26 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +	vddb-supply = <&pm8916_s4>;
https://github.com/msm8916-mainline/linux/blob/master/drivers/gpu/drm/msm/dsi/dsi_cfg.c#L57-L58
`vdd` and `vddb` are not defined.

2022-02-08 08:26 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		power-supply = <&pm8916_l17>;
https://github.com/msm8916-mainline/linux/commit/17e30b38faa37d1e8cccb921f88c15e2153017f7#diff-92c2357e6d8e3028d5884f443969796f7d690bd991dc913f8f1fdd23575c14b2R65-R66
J5 has similar power supplies but the panel don't actually work with J5 device tree on J3.

2022-02-28 18:34 UTC, stephan-gh requested changes
Please rename the file and device tree to `j3ltetw` as I suggested on Matrix. Let's deal with other variants only when someone shows up who has them.

2022-02-28 18:59 UTC, wonderfulShrineMaidenOfParadise commented
I don't have a special preference but the codename could be `j3ltezt`.

2022-03-01 13:34 UTC, stephan-gh requested changes

2022-03-01 13:34 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +			/* HACK: Replace with SM5703 MUIC when driver is available */
Have you tried all MUIC functionality? Check `/sys/class/extcon/.../state` and see if `USB=1` if USB cable is connected (`USB=0` if it's not connected). Ideally, if you have an USB-OTG cable also check if `USB-HOST=1` if the cable is connected.

If everything is working properly there is probably no need to mark this as a "hack". In that case we should probably simply add a `siliconmitus,sm5703-muic` compatible to the sm5502 driver with the same configuration as sm5502.

2022-03-01 13:44 UTC, stephan-gh requested changes

2022-03-01 13:44 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +	 *      For J320P and J320R4, use i2c1
If you want to keep these comments please format them properly like

```c
/*
 * NOTE: For ...
 * Hello World!
 * Why am I spending so much time writing an example comment?
 * Please just stop reading.
 * OK. Bye.
 */
```

2022-03-01 13:44 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +		regulator-max-microvolt = <3100000>;
Looks like this should be min = max = 3000000?

https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/a516b4516645bace35af1bfb2d1ab3d398f929cb/arch/arm/boot/dts/samsung/msm8916/msm8916-sec-j3lte-chnctc-r05.dtsi#L604-L612

(please check if this is even the correct device tree)

2022-03-01 13:47 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3.dts
> +		/*NOTE For J320P and J320R4 use i2c3 */
Renamed it to `j3ltetw`.

2022-03-01 14:17 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +	 *      For J320P and J320R4, use i2c1
Dropped the comments. The wiki page also has this documented.

2022-03-01 17:19 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +			/* HACK: Replace with SM5703 MUIC when driver is available */
Result: https://paste.debian.net/1232650/
Dropping `HACK`.

2022-03-02 09:31 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +		power-supply = <&pm8916_l17>;
This doesn't really seem right, might as well omit the supplies when using panel-simple so everything stays on.

2022-03-05 12:33 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +		power-supply = <&pm8916_l17>;
l17 is still required. Without this line, panel works in initramfs, but it will turn off before login prompt.

2022-03-07 00:37 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +			/* HACK: Replace with SM5703 MUIC when driver is available */
I guess there is a volunteer working on SM5703 upstreaming.

2022-03-14 08:36 UTC, stephan-gh commented
Pushed to rebase, thanks!

2022-03-14 08:36 UTC, closed without merging