arm64: dts: qcom: msm8916-samsung-e7: Add initial dts
msm8916-mainline/linux pull request #215
Opened 2022-01-04 14:16 UTC by wonderfulShrineMaidenOfParadise

This dts adds support for Samsung Galaxy E7 smartphone released in 2015.

Unfortunately, some variants were released with outdated 32-bit only
firmware and never received any update from Samsung. Since the 32-bit
TrustZone firmware is signed there seems to be no way currently to
actually boot this device tree on arm64 Linux at the moment. :(

However, it is possible to use this device tree by compiling an ARM32 kernel
instead. The device tree can be easily built on ARM32 with an #include
and it works really well there. To avoid confusion for others it is still
better to add this device tree on arm64. Otherwise it's easy to forget
to update this one when making some changes that affect all MSM8916 devices.

Maybe someone finds a way to boot ARM64 Linux on this device at some point.
In this case I expect that this device tree can be simply used as-is.

2022-01-04 14:59 UTC, wonderfulShrineMaidenOfParadise commented
https://github.com/msm8916-mainline/linux-panel-drivers/pull/9 is created to automatically generate the panel driver.
`ea8061-id400418` is the used one.

2022-01-04 15:01 UTC, wonderfulShrineMaidenOfParadise commented on drivers/gpu/drm/panel/msm8916-generated/Makefile
> +obj-$(CONFIG_DRM_PANEL_MSM8916_GENERATED) += panel-samsung-ea8061-id400418.o
https://github.com/msm8916-mainline/linux-panel-drivers/pull/9 is created to automatically generate the panel driver.

2022-01-04 15:03 UTC, wonderfulShrineMaidenOfParadise commented on drivers/input/touchscreen/stmfts.c
> -		return -ETIMEDOUT;
It looks not right to drop it completely. Maybe raise the timeout interval.

2022-01-14 01:14 UTC, wonderfulShrineMaidenOfParadise commented on drivers/input/touchscreen/stmfts.c
> -		return -ETIMEDOUT;
It seems there is non-true stuff returned with `&sdata->cmd_done`. Need some help from the author.
I don't see `mms114` or `zinitix` using this, though.

2022-01-22 09:15 UTC, wonderfulShrineMaidenOfParadise commented on drivers/input/touchscreen/stmfts.c
> +		case STMFTS_EV_HACK:
`0x80` is received during init but not handled. Consider it expected.

2022-01-22 09:19 UTC, wonderfulShrineMaidenOfParadise commented on drivers/input/touchscreen/stmfts.c
> +	return -ETIMEDOUT;
It seems that it's the timeout length, but the count of attempts `wait_for_completion_timeout()`.
Some commands require at least 2 attempts to complete.
https://paste.debian.net/1227992/

2022-01-22 20:03 UTC, wonderfulShrineMaidenOfParadise commented on drivers/input/touchscreen/stmfts.c
> +			 "failed to perform system reset: %d\n", err);
```
postmarketos-msm8916:~$ dmesg |grep stmfts
[    0.512347] stmfts 6-0049: starting command 0x80
[    0.537347] stmfts 6-0049: event 0x80 received
[    0.537360] stmfts 6-0049: unknown event 0x80
[    0.537366] stmfts 6-0049: event 0x0 received
[    0.572385] stmfts 6-0049: starting command 0xa0
[  102.960609] stmfts 6-0049: failed to perform system reset: -110
[  102.961314] stmfts 6-0049: starting command 0x91
[  102.986226] stmfts 6-0049: event 0x11 received
[  102.987093] stmfts 6-0049: Received event in 1000 ms
[  102.987714] stmfts 6-0049: starting command 0xa3
[  103.401054] stmfts 6-0049: event 0x16 received
[  103.401807] stmfts 6-0049: Received event in 1000 ms
[  103.402433] stmfts 6-0049: starting command 0xa4
[  103.490250] stmfts 6-0049: event 0x16 received
[  103.491004] stmfts 6-0049: Received event in 1000 ms
[  103.491626] stmfts 6-0049: starting command 0xa2
[  103.541450] stmfts 6-0049: event 0x16 received
[  103.542203] stmfts 6-0049: Received event in 1000 ms
[  103.543840] input: stmfts as /devices/platform/soc/78b9000.i2c/i2c-6/6-0049/input/input4
```
Waiting for a reply from the author of stmfts, Andi, to understand how to receive an event.

2022-01-22 22:39 UTC, wonderfulShrineMaidenOfParadise commented
A potential solution https://github.com/msm8916-mainline/linux/pull/215/commits/38627bd622cc7cda4317f2381f02b45f479a41bb has been found.
Reference: https://lxr.trvn.ru/linux_qcom_msm8916/SM-E7000/source/drivers/input/touchscreen/stm_fts/fts_ts.c#L283

2022-02-08 13:43 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-e7.dts
> +		compatible = "samsung,e7-panel";
https://github.com/msm8916-mainline/lk2nd/pull/144 is created for panel selection.

2022-02-17 11:50 UTC, wonderfulShrineMaidenOfParadise reviewed
Upstreaming for stmfts has been planned.

2022-03-02 09:46 UTC, stephan-gh requested changes

2022-03-02 11:27 UTC, stephan-gh approved these changes

2022-03-02 17:20 UTC, TravMurav approved these changes

2022-03-03 11:13 UTC, stephan-gh commented
Integrated into `rebase42` branch, thanks!

2022-03-03 11:13 UTC, closed without merging