arm64: dts: qcom: msm8916-samsung-j5x: Add initial dts (v5)
msm8916-mainline/linux pull request #224
Opened 2022-02-26 14:52 UTC by wonderfulShrineMaidenOfParadise

- Update Hall sensor, MUIC and WCNSS
- K2HH Accelerometer
- Modem and sound
- Audio jack

2022-03-01 13:57 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5x.dts
> +		};
TODO: https://github.com/msm8916-mainline/linux/pull/207#discussion_r816772280

2022-03-01 18:35 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5x.dts
> +				       "0", "0", "1";
```c
			k2hh@1D {
				compatible = "stm,k2hh";
				reg = <0x1d>;
				interrupt-parent = <0x46>;
				interrupts = <0x31 0x00>;
				stm,irq_gpio = <0x46 0x31 0x00>;
				stm,vio-supply = <0x50>;
				stm,axis_map_x = <0x01>;
				stm,axis_map_y = <0x00>;
				stm,axis_map_z = <0x02>;
				stm,negate_x = <0x00>;
				stm,negate_y = <0x01>;
				stm,negate_z = <0x01>;
				stm,poll_interval = <0x64>;
				stm,min_interval = <0x02>;
			};
```

2022-03-01 18:35 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5x.dts
> +	};
```c
			k2hh@1D {
				compatible = "stm,k2hh";
				reg = <0x1d>;
				interrupt-parent = <0x46>;
				interrupts = <0x31 0x00>;
				stm,irq_gpio = <0x46 0x31 0x00>;
				stm,vio-supply = <0x50>;
				stm,axis_map_x = <0x01>;
				stm,axis_map_y = <0x00>;
				stm,axis_map_z = <0x02>;
				stm,negate_x = <0x00>;
				stm,negate_y = <0x01>;
				stm,negate_z = <0x01>;
				stm,poll_interval = <0x64>;
				stm,min_interval = <0x02>;
			};
```

2022-03-01 18:51 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5x.dts
> +				       "0", "0", "1";
```suggestion
				       "0", "0", "-1";
```

2022-03-10 10:51 UTC, stephan-gh requested changes

2022-03-10 10:51 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5x.dts
> +		"AMIC2", "MIC BIAS Internal2",
Have you tested if this works properly (tried recording audio from headset microphone)?

This seems related to https://github.com/msm8916-mainline/linux/pull/189/files#r621162048 downstream, perhaps we can just assume it's same on j5 2015 and 2016.

2022-03-10 11:54 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5x.dts
> +		"AMIC2", "MIC BIAS Internal2",
Headset microphone is broken with this. Trying to fix it.

2022-03-10 13:26 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5x.dts
> +	pinctrl-0 = <&jack_default>;
Headphone buttons are broken as well.

2022-03-14 07:55 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5x.dts
> +		"AMIC2", "MIC BIAS Internal2",
Same commit works on j3ltezt. However there are things to figure out:
- Is my j5x jack broken?
- Are jacks on j5x and j3ltezt similar?

2022-03-14 08:37 UTC, stephan-gh commented
Pushed to rebase as-is for now, if you figure out what's wrong with the headset mic (or maybe it's really just your device?), then feel free to push additional squash!/fixup! commits.

2022-03-14 08:37 UTC, closed without merging