arm64: dts: qcom: Add dt for fortuna3g
msm8916-mainline/linux pull request #225
Opened 2022-03-07 13:57 UTC by SiddharthManthan

This pull request adds support for gprime and fortuna3g devices.

Add initial support for :
* gpio keys and WCNSS
* Vibrator
* rt5033 fuelgauge. Also compatible with sec-fuelgauge
* Zinitix BT541 with touchkey
* Modem and sound
* Audio jack

The following pull requests need to merged first :
- [ ] Update Kernel to 5.17
- [ ] https://github.com/msm8916-mainline/lk2nd/pull/151
- [ ] https://github.com/msm8916-mainline/linux-panel-drivers/pull/10

2022-03-07 14:13 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-fortuna3g.dts
> -		tz-apps@85a00000 {
this change seem to be in a wrong commit

2022-03-07 14:45 UTC, wonderfulShrineMaidenOfParadise requested changes

2022-03-07 14:45 UTC, wonderfulShrineMaidenOfParadise commented on drivers/gpu/drm/panel/msm8916-generated/Makefile
> -obj-$(CONFIG_DRM_PANEL_MSM8916_GENERATED) += panel-samsung-ea8061-ams549bu19-id400418.o
Same here.

2022-03-07 14:45 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/Makefile
> -dtb-$(CONFIG_ARCH_QCOM)	+= msm8916-samsung-e7.dtb
Well my E7 is just merged please don't drop it  so quickly :p

2022-03-13 13:22 UTC, stephan-gh commented
Closing in favor of https://github.com/msm8916-mainline/linux/pull/227 (I guess)

2022-03-13 13:22 UTC, closed without merging