arm64: dts: qcom: msm8916-samsung-gprime: Add gprimeltecan and fortuna3g
msm8916-mainline/linux pull request #227
Opened 2022-03-13 11:26 UTC by wonderfulShrineMaidenOfParadise

Closes #225 

Samsung Galaxy Grand Prime is a smartphone using the MSM8916
SoC released in 2014.

The Grand Prime variants are very similar, with some differences in
accelerometer, NFC and panel. The common parts are shared in
msm8916-samsung-gprime.dts to reduce duplication.

Create a common dtsi, which can be reused by the other gprime/fortuna variants.

Changes:
- GPIO keys and WCNSS
- Vibrator
- rt5033 fuelgauge. Also compatible with sec-fuelgauge
- Panel selection in lk2nd
- Zinitix BT541 with touchkey
- Modem and sound
- Audio jack

gprimeltecan:
- reserved memory for gprimeltecan
- BMC150 accelerometer for gprimeltecan

fortuna3g:
- K2HH accelerometer for fortuna3g
- s6d78a0-gh9607501a panel for fortuna3g

2022-03-13 14:50 UTC, stephan-gh requested changes
Looks good mostly, just some minor comments. :)

2022-03-13 14:50 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gprime-common.dtsi
> +		vreg-supply = <&pm8916_l6>;
`vreg-supply` sounds weird. I'd either call this supply `vddio-supply` or simply drop it (toss a coin if you want). [L6 is already enabled/disabled as needed for dsi0](https://github.com/msm8916-mainline/linux/blob/edd4ec00a14e682b8a2ad7090131138372f54d11/arch/arm64/boot/dts/qcom/msm8916-pm8916.dtsi#L12).

cc @SiddharthManthan for https://github.com/msm8916-mainline/linux-panel-drivers/pull/12 (please coordinate who will make this change)

2022-03-13 14:50 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gprime-common.dtsi
> +		vddo-supply = <&pm8916_l6>;
Please use the new supply names (see https://github.com/msm8916-mainline/linux/commit/c54be0e32e54abdf7b89d56fe9edebc2f319acee). It should be:

```
vcca-supply = <&reg_vdd_tsp_a>;
vdd-supply = <&pm8916_l6>;
```

2022-03-13 14:50 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gprimeltecan.dts
> +	};
The reserved-memory for gprimeltecan and fortuna3g seems identical, can we put it into the common dts?

NOTE: If fortunaltezt is different here this is exactly the situation where I need the full changes to be able to review properly. If yes, please push the fortunaltezt changes to this branch. I can skip them when merging if they are not fully ready but I would like to consider them in my review.

2022-03-13 14:50 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gprimeltecan.dts
> +		vdd-supply = <&pm8916_l17>;
Looks like this should also be `&pm8916_l5` according to downstream:

https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/74c765e8c74df57881b6c94d4eda1b4d2a9ecda7/arch/arm/boot/dts/samsung/msm8916/msm8916-sec-fortuna-tmo-r02.dtsi#L199-L200

2022-03-13 14:50 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gprimeltecan.dts
> +		vdd-supply = <&pm8916_l17>;
same here

2022-03-13 14:50 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-fortuna3g.dts
> +	panel@0 {
I'd prefer `&panel { ... }` on top level, rather than &dsi -> panel@0.

2022-03-13 14:50 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-fortuna3g.dts
> +		};
I'd drop this and put it in the common dtsi as written in an earlier comment.

2022-03-13 18:12 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gprime-common.dtsi
> +		vreg-supply = <&pm8916_l6>;
I would leave s6d78a0-gh9607501a in l-p-d to @SiddharthManthan. On the other hand I am working on hx8389c/hx8389c-gh9607501a.

2022-03-13 23:17 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gprimeltecan.dts
> +	};
Pushed fortunaltezt changes.

2022-03-14 08:58 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gprimeltecan.dts
> +	};
I'd put the reserved-memory in the common dtsi. You have two options (toss a coin again if you want):

- Use the 0x5a00000 for all gprimes (this will waste 2 MiB RAM on most variants)
- Use 0x5800000 in the common dtsi and override it for fortunaltezt like this:

```
	reserved-memory {
		/delete-node/ gps@8c000000;

		mpss_mem: mpss@86800000 {
			reg = <0x0 0x86800000 0x0 0x5a00000>;
			no-map;
		};

		gps_mem: gps@8c200000 {
			reg = <0x0 0x8c200000 0x0 0x200000>;
			no-map;
		};
	};
```

2022-03-14 12:57 UTC, SiddharthManthan commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gprimeltecan.dts
> +	};
Overriding is preferred as ram is a luxury on fortuna3g.

2022-03-16 15:50 UTC, SiddharthManthan commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gprimeltecan.dts
> +	};
Resolved. No need to commonize ram.

2022-03-17 11:32 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-fortunaltezt.dts
> +		};
Todo: Smaller value

2022-03-17 11:32 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gprimeltecan.dts
> +		};
Todo: Smaller value

2022-03-17 11:32 UTC, wonderfulShrineMaidenOfParadise commented on drivers/gpu/drm/panel/msm8916-generated/panel-samsung-hx8389c.c
> +	ctx->supplies[0].supply = "vreg";
```suggestion
	ctx->supplies[0].supply = "vddio";
```

Todo: Update l-p-d script

2022-03-18 15:40 UTC, SiddharthManthan commented
I will leave generating the panel drivers to @wonderfulShrineMaidenOfParadise as I don't know what changes were made to the panel drivers.

2022-03-21 10:39 UTC, stephan-gh commented
See https://github.com/msm8916-mainline/linux/pull/228

2022-03-21 10:39 UTC, closed without merging