arm64: dts: qcom: msm8916-samsung-j5-common: Add init device tree (v2)
msm8916-mainline/linux pull request #237
Opened 2022-04-23 01:23 UTC by wonderfulShrineMaidenOfParadise

cc @LorenDB @marohinmark @mintphin @nergzd723

2022-04-23 03:34 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5-common.dtsi
> +		compatible = "samsung,s6e8aa5x01-ams497hy01";
It's compatible with `s6e8aa5x01-ams520kt01` on J5X as well. Dedicated `panel-simple` driver is in #233.

2022-04-23 03:34 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5-common.dtsi
> +};
Rewrite of #189. It works on J3 and J5, but not J5X. Could be caused by a missing l5 regulator.

2022-04-23 03:37 UTC, wonderfulShrineMaidenOfParadise reviewed
(duplicated comment)

2022-04-23 03:38 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +	scl-gpios = <&msmgpio 7 (GPIO_ACTIVE_HIGH|GPIO_OPEN_DRAIN)>;
Also known as i2c2

2022-04-24 10:13 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +		/delete-node/ gps@8c000000;
```suggestion
```
The reserved memory should be same as J5/J5X.

2022-05-03 07:51 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5x.dts
>  	};
Todo: verify l17 voltage.

2022-05-07 01:54 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5x.dts
>  	};
I am advised to supply constant 3v0 for sensors.

2022-05-15 11:09 UTC, stephan-gh commented
@wonderfulShrineMaidenOfParadise Please have just one PR for all the J5 changes and close all the other ones. I'm getting real confused otherwise :)

2022-05-15 16:34 UTC, wonderfulShrineMaidenOfParadise commented
This is active one. The other PRs are closed to avoid confusion.

2022-05-24 22:49 UTC, wonderfulShrineMaidenOfParadise commented
- Rebase on `rebase` 5.18
- Add imagis tsp

2022-05-24 22:52 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5-common.dtsi
> +		compatible = "samsung,s6e8aa5x01-ams497hy01";
There are also full generated panel drivers with clock issues fixed.
msm8916-mainline/linux-mdss-dsi-panel-driver-generator#17 is required.

2022-05-26 18:43 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5-common.dtsi
> +		compatible = "samsung,s6e8aa5x01-ams497hy01";
Can you make the linux-panel-drivers PR? I merged the generator fix (feel free to update the submodule in linux-panel-drivers)

2022-05-26 18:43 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5-common.dtsi
> +};
l5 should be always-on, so shouldn't make any difference :S

2022-05-26 18:57 UTC, stephan-gh requested changes

2022-05-26 18:57 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5-common.dtsi
> -	chassis-type = "handset";
A part of the `msm8916-samsung-j5.dts` file is already upstream. This means I have no commit I could squash the "init device v2" commit into. We need to make clean commits on top. Please do the following:

- Start a new branch based on `rebase` (without your changes)
- Revert the existing changes made to `msm8916-samsung-j5.dts`, i.e.:
  - https://github.com/msm8916-mainline/linux/commit/ae921a205f1f218f74b9dd168ec116c70cb64c0a
  - https://github.com/msm8916-mainline/linux/commit/4d181a8d78aaa389efb3c18fdc2fd58f77ae913d
  - https://github.com/msm8916-mainline/linux/commit/871b95e942d3cd460d0eba900ebb4d042493743b
- Make a clean commit that moves the relevant parts from `msm8916-samsung-j5.dts` to the `-common.dtsi`.
- Add additional functionality etc on top using additional commits (as usual).

j5x is not upstream yet so this approach is not necessary for it.

2022-05-26 21:34 UTC, geraldog commented
@wonderfulShrineMaidenOfParadise please keep me in the loop for next PR. Thanks!

2022-05-27 13:14 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5-common.dtsi
> +		compatible = "samsung,s6e8aa5x01-ams497hy01";
msm8916-mainline/linux-panel-drivers#15 is opened.

2022-05-27 13:15 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5-common.dtsi
> -	chassis-type = "handset";
Rebased with the changes above.

2022-05-28 05:07 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5-common.dtsi
> -	chassis-type = "handset";
Pushed with clean branch.

2022-05-28 12:42 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5-common.dtsi
> +// SPDX-License-Identifier: GPL-2.0-only
For `arm64: dts: qcom: msm8916-samsung-j5: Add common init device tree`: The commit message should say that you are moving parts to a common .dtsi. Right now it sounds like you're adding a completely new device tree.

2022-05-28 12:42 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +	/delete-node/ gpio-hall-sensor;
It's probably cleaner to just set it to `status = "disabled"` in this case.

2022-05-28 12:42 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +	/* HACK l17 is a quirk to power up panel */
Why is this a hack?

2022-05-28 13:13 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +	/* HACK l17 is a quirk to power up panel */
It comes my random trial and error results and I still don't understand why it works.

2022-05-28 13:15 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5-common.dtsi
> +// SPDX-License-Identifier: GPL-2.0-only
Reworded as `arm64: dts: qcom: msm8916-samsung-j5: Use common init device tree`

2022-05-28 13:16 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +	/delete-node/ gpio-hall-sensor;
```c
	gpio-hall-sensor {
		status = "disabled";
	};
```
Applied this.

2022-05-28 15:31 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +	gpio-hall-sensor {
Please add a label for it and reference it:

```
&gpio_hall_sensor {
	status = "disabled";
};
```

Also, the commit message mentions that the hall sensor is working... :p

2022-05-28 15:31 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +			reg = <0x0 0x85800000 0x0 0x800000>;
AFAICT j3ltetw has the same amount reserved as the j5s?

https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/1771d3fabf92485c863f2c5450cb1b75e4f472a3/arch/arm/boot/dts/samsung/msm8916/msm8916-memory.dtsi#L20-L29

https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/a516b4516645bace35af1bfb2d1ab3d398f929cb/arch/arm/boot/dts/samsung/msm8916/msm8916-memory.dtsi#L21-L30

2022-05-28 15:31 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +	/* HACK l17 is a quirk to power up panel */
Have you tried using a fixed regulator on gpio 102?

2022-05-28 15:31 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5x.dts
> +	vdd-supply = <&reg_vdd_tsp_a>;
this is already set like this in j5-common?

2022-05-28 15:31 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5.dts
> +	vdd-supply = <&pm8916_l17>;
afaict this is both l5

2022-05-28 17:00 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5.dts
> +	vdd-supply = <&pm8916_l17>;
Schematics suggests both l5 as well. Will set it to l5.

2022-05-28 17:08 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +			reg = <0x0 0x85800000 0x0 0x800000>;
https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/1771d3fabf92485c863f2c5450cb1b75e4f472a3/arch/arm/boot/dts/samsung/msm8916/msm8916-sec-j3lte-chntw-r00.dts#L32-L34
This overrides `msm8916-memory.dtsi`.

2022-05-28 17:16 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +	/* HACK l17 is a quirk to power up panel */
Worth trying after I have learnt something new.

2022-05-28 21:47 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +	/* HACK l17 is a quirk to power up panel */
Still not possible. Once I trying to play with gpio 102, the panel will be disabled and become pitch black.
And I still need to keep l17 enabled. Can be set as supply voltage of something or set`regulators-always-on`.

2022-05-28 23:43 UTC, wonderfulShrineMaidenOfParadise commented
- Revert `panel-simple` commit for `samsung,s6e8aa5x01-ams497hy01`
- Keep l17 always on for J3
- Add not so necessary fixed regulator on GPIO 102

2022-05-28 23:45 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +	/* HACK l17 is a quirk to power up panel */
Fixed regulator on gpio 102 doesn't seem to break the panel now, but l17 is still required, otherwise the panel will become black after initfs loaded.

2022-05-29 00:04 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5.dts
>  	qcom,init-seq = /bits/ 8 <0x1 0x19 0x2 0x0b>;
Todo: check this property.

2022-05-29 10:21 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5.dts
>  	qcom,init-seq = /bits/ 8 <0x1 0x19 0x2 0x0b>;
https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/d82d98ae10d4c114b481b10d4a51359dadd9b58a/arch/arm/boot/dts/samsung/msm8916/msm8916-sec-j5nlte-eur-r05.dtsi#L479

This is some USB calibration value that may or may not improve USB reliability. Iirc this helped for the person who originally ported J5

2022-05-29 10:35 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltetw.dts
> +			reg = <0x0 0x85a00000 0x0 0xe00000>;
0xe00000 is wrong as well though because you should just cover the additional part until 0x86000000. Everything else is already reserved in msm8916.dtsi

This should be `0x600000` like in fortuna3g

https://github.com/msm8916-mainline/linux/blob/a1839536da3e7f8a637ab46989345da429433960/arch/arm64/boot/dts/qcom/msm8916.dtsi#L41-L81

2022-05-29 14:32 UTC, wonderfulShrineMaidenOfParadise commented
- Refactored panel regulators
- Drop l17 quirk on J3 and use it as `vin-supply = <&pm8916_l17>;` for panel regulator

2022-05-29 15:09 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5-common.dtsi
> +	reg_vdd_lcd_1p8: regulator-vdd-lcd-1p8 {
I'm not sure if this is a bit "over-commonized" given that the gpios seem to vary a lot between the devices. (I'm somewhat leaning to yes, but not enough to force you to change it back. Consider just defining the fixed regulators separately for each device though)

Anyway, if you keep it like this please set incomplete nodes `status = "disabled";` by default and then enable them when their configuration is finished:

```
&reg_vdd_lcd_1p8 {
	status = "okay";
	gpio = <&msmgpio 16 GPIO_ACTIVE_HIGH>;
};
```

2022-05-29 15:55 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-j5-common.dtsi
> +	reg_vdd_lcd_1p8: regulator-vdd-lcd-1p8 {
To be honest I am afraid so as well. I may fix and set it disabled by default, or reduce some commonized parts e.g. panel and touchscreen.

2022-06-04 11:27 UTC, stephan-gh approved these changes

2022-06-04 12:08 UTC, stephan-gh commented
Pushed to rebase

2022-06-04 12:08 UTC, closed without merging