arm64: dts: qcom: msm8916-samsung-cprime: Add initial device tree
msm8916-mainline/linux pull request #239
Opened 2022-05-01 09:59 UTC by wonderfulShrineMaidenOfParadise

Samsung Galaxy Core Prime is a phone based on MSM8916. It is similar
to the other Samsung devices based on MSM8916 with only a few minor
differences.

The device tree contains initial support for the Grand Prime with:
- GPIO keys
- Hall sensor
- SDHCI (internal and external storage)
- USB Device Mode
- UART
- WCNSS (WiFi/BT)
- Regulators

Core Prime and Grand Prime are similar, with some differences in
accelerometer, MUIC, NFC, panel and touchscreen. The common parts are
shared in msm8916-samsung-gprime-common.dtsi to reduce duplication.

2022-05-01 11:00 UTC, wonderfulShrineMaidenOfParadise commented
We may need to decide which codename to use:
- `cprimelte`
- `coreprimelte`
- `rossalte`

3G variants are not `MSM8916` phones

2022-05-07 00:57 UTC, wonderfulShrineMaidenOfParadise commented
For reference purpose I added Ace device tree. They are quite similar.

2022-05-18 22:51 UTC, wonderfulShrineMaidenOfParadise commented
Todo: reword. `s/Ace 4/Ace Style/`

2022-05-19 06:07 UTC, wonderfulShrineMaidenOfParadise commented
Refactored NFC in `msm8916-samsung-gprime-common.dtsi`.

2022-05-20 23:46 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-heatqlte.dts
> +	};
https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/SM-G357FZ/arch/arm/boot/dts/samsung/msm8916-memory.dtsi#L27

```
$ ./mbndump.py modem.mdt | grep Size
Size: 0x4f00000, round: 0x5000000
```

Could be smaller.

2022-05-20 23:46 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-heatqlte.dts
> +	/* Cyttsp4 touchscreen instead of BT541 */
```suggestion
	/* Cyttsp4 touchscreen instead of Imagis IST3038B */
```

Since it includes ` msm8916-samsung-cprime.dts`.

2022-05-20 23:46 UTC, wonderfulShrineMaidenOfParadise commented on drivers/gpu/drm/panel/msm8916-generated/Makefile
> +obj-$(CONFIG_DRM_PANEL_MSM8916_GENERATED) += panel-samsung-s6288a0.o
Todo: move to `../`

2022-05-22 09:37 UTC, wonderfulShrineMaidenOfParadise commented
- No memory relocation for `heatqlte`
- Use `heatqlte` as the base of `cprime`
- Move `samsung-s6288a0` panel driver

2022-05-26 19:05 UTC, stephan-gh requested changes

2022-05-26 19:05 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-gprime-common.dtsi
> +		status = "okay";
I think I'd prefer an opt-in approach here. Keep it disabled as it was before and then just enable it where needed.

2022-05-26 19:05 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-heatqlte.dts
> +	compatible = "siliconmitus,sm5504-muic";
weird indentation

2022-05-26 19:05 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-heatqlte.dts
> +#include "msm8916-samsung-fortunaltezt.dts"
Interesting choice (fortunaltezt instead of gprime-common). Can you briefly explain the reason for that in the commit message?

2022-05-26 19:05 UTC, stephan-gh commented on drivers/gpu/drm/panel/Kconfig
> +config DRM_PANEL_SAMSUNG_S6288A0
Why is this not generated by linux-panel-drivers? Maybe @garethppls just needs to add the configuration there.

2022-05-27 08:18 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-heatqlte.dts
> +#include "msm8916-samsung-fortunaltezt.dts"
I am not so sure about doing this.
This will reuse:
- Reserved memory
- `st,lis2hh12` accelerometer including property `mount-matrix`
- Disabled PWM backlight

2022-05-27 08:18 UTC, wonderfulShrineMaidenOfParadise commented on drivers/gpu/drm/panel/Kconfig
> +config DRM_PANEL_SAMSUNG_S6288A0
3baa285ad53540f8cb8c0474e864245ded1a1657 is added so I assume this driver will be moved.

2022-05-27 08:18 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-cprime.dts
> +#include "msm8916-samsung-heatqlte.dts"
Not sure about this coding style.

2022-05-27 08:18 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm/boot/dts/qcom-msm8916-samsung-heatqlte.dts
> +};
Note: this was required for 32-bit cprime originally.

2022-05-27 11:04 UTC, stephan-gh commented on drivers/gpu/drm/panel/Kconfig
> +config DRM_PANEL_SAMSUNG_S6288A0
We don't move the drivers just because adding a single line. There are other examples for minor fix-ups in https://github.com/msm8916-mainline/linux/commits/rebase/drivers/gpu/drm/panel/msm8916-generated. Just add it as additional commit and it will be fine.

2022-05-27 15:01 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-heatqlte.dts
> +#include "msm8916-samsung-fortunaltezt.dts"
I think it's a bit exaggerated maybe. Let's make all the devices include the gprime-common.dtsi and then duplicate certain settings if needed.

2022-05-28 03:31 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-heatqlte.dts
> +#include "msm8916-samsung-fortunaltezt.dts"
Right, using `gprime-common.dtsi`.
By the way do we need to create new `cprime-common.dtsi`? Could be used by cprime and heatqlte, with same stuffs:
- SM5504 MUIC
- `s3fwrn5` nfc
- `lis2hh` accelerometer
- Disabled `bt541` touchscreen

2022-05-28 12:31 UTC, wonderfulShrineMaidenOfParadise commented
- Keep `i2c_nfc` disabled by default
- Use `msm8916-samsung-cprime-common.dtsi`

2022-05-28 12:45 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-cprime-common.dtsi
> +	/* IST3038 touchscreen instead of BT541 */
The comment doesn't seem right since heatqlte has something different

2022-05-28 12:45 UTC, stephan-gh commented on drivers/gpu/drm/panel/msm8916-generated/Makefile
> +obj-$(CONFIG_DRM_PANEL_MSM8916_GENERATED) += panel-samsung-s6288a0.o
need the linux-panel-drivers change for this (actually this doesn't seem to be generated by linux-panel-drivers which is bad)

2022-05-28 13:22 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-cprime-common.dtsi
> +	/* IST3038 touchscreen instead of BT541 */
Maybe `s/IST3038 touchscreen/Various of touchscreens/`

2022-05-29 00:20 UTC, wonderfulShrineMaidenOfParadise commented on drivers/gpu/drm/panel/msm8916-generated/Makefile
> +obj-$(CONFIG_DRM_PANEL_MSM8916_GENERATED) += panel-samsung-s6288a0.o
@garethppls Please handle submit the configs and dtb on msm8916-mainline/linux-panel-drivers repo :)

2022-05-29 10:37 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-cprime-common.dtsi
> +	/* IST3038 touchscreen instead of BT541 */
That sounds like a device might have _multiple_ touchscreens. Worst case just drop the comment if we cannot come up with a good one :p

2022-06-28 09:14 UTC, garethppls commented
Tested on heatqlte with XFCE4 (key bindings didn't work here for some reason), and on Phosh (keybindings worked).

2022-06-28 18:17 UTC, stephan-gh commented on drivers/gpu/drm/panel/msm8916-generated/Makefile
> +obj-$(CONFIG_DRM_PANEL_MSM8916_GENERATED) += panel-samsung-s6288a0.o
Yes, we will keep the extra commit you made on top https://github.com/msm8916-mainline/linux/pull/239/commits/606e097e240f0d18046babd8cce692b083e9b693. There are existing examples for this e.g. https://github.com/msm8916-mainline/linux/commits/master/drivers/gpu/drm/panel/msm8916-generated/panel-samsung-s6e88a0-ams427ap24.c

2022-06-29 18:20 UTC, garethppls commented on drivers/gpu/drm/panel/msm8916-generated/Makefile
> +obj-$(CONFIG_DRM_PANEL_MSM8916_GENERATED) += panel-samsung-s6288a0.o
Review is open for this one on linux-panel-drivers

2022-07-01 19:01 UTC, stephan-gh approved these changes

2022-07-07 04:16 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-cprime.dts
> +	compatible = "samsung,cprime-panel";
Can we have this in a dedicated commit "add the display panel" so the other more easily upstreamable part is separated?

Also I think the gprime-common.dtsi already uses a generic compatible for panel selection (`gprime-panel`), have you considered re-using that or maybe redefining this in cprime-common and leaving this for lk2nd to deal with?

2022-07-07 04:16 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-samsung-heatqlte.dts
> +	compatible = "samsung,s6288a0";
same

2022-07-08 18:33 UTC, TravMurav approved these changes

2022-07-08 18:33 UTC, merged