arm64: dts: qcom: msm8916-samsung-grandmax: Add initial device tree
msm8916-mainline/linux pull request #240
Opened 2022-05-11 19:02 UTC by wonderfulShrineMaidenOfParadise

Samsung Galaxy Grand Max is a phone based on MSM8916. It is
similar to the other Samsung devices based on MSM8916 with only a few
minor differences.

The device tree contains initial support for the Core Prime with:
- GPIO keys
- SDHCI (internal and external storage)
- USB Device Mode (on USB connector via the SM5504 MUIC)
- UART
- WCNSS (WiFi/BT)
- Regulators
- Fuelgauge (`sec-fuelgauge`compatible with `richtek,rt5033-battery`)
- Accelerometer LIS2HH
- Sound and modem with amp `nxp,tfa9895`
- Audio jack

2022-05-25 03:49 UTC, wonderfulShrineMaidenOfParadise commented
Without backlight support for the panel, this phone seems to be a low priority device.

2022-05-25 23:41 UTC, wonderfulShrineMaidenOfParadise commented
- Use `msm8916-samsung-a2015-common.dtsi`
- Add backlight and panel. The brightness is not adjustable.

2022-05-26 19:08 UTC, stephan-gh requested changes

2022-05-26 19:08 UTC, stephan-gh commented on drivers/gpu/drm/panel/msm8916-generated/panel-samsung-s6d2aa0x62-lpm053a250a.c
> +			  MIPI_DSI_MODE_NO_EOT_PACKET | MIPI_DSI_CLOCK_NON_CONTINUOUS;
Why? (Please add better commit message)

2022-05-27 08:07 UTC, wonderfulShrineMaidenOfParadise commented on drivers/gpu/drm/panel/msm8916-generated/panel-samsung-s6d2aa0x62-lpm053a250a.c
> +			  MIPI_DSI_MODE_NO_EOT_PACKET | MIPI_DSI_CLOCK_NON_CONTINUOUS;
```
If panel uses both high-speed and low-power mode, set MIPI_DSI_CLOCK_NON_CONTINUOUS. Check the -command-state fields for dsi_lp_mode and dsi_hs_mode. If you see both, then set MIPI_DSI_CLOCK_NON_CONTINUOUS since we are switching dynamically between different speeds. There's a catch though - another field (dsi-force-clk-lane-hs)
exists, which indicates that only high-speed mode is used. The issue
is, some downstream kernels may use both of these fields, and even set
them different to one another. In that case, dsi-force-clk-lane-hs takes
precedence, and you can safely ignore the -command-state fields.
```
Reference: https://github.com/freedreno/freedreno/wiki/DSI-Panel-Driver-Porting#translating-dsi-configuration

```c
		qcom,mdss-dsi-on-command-state = "dsi_lp_mode";
		qcom,mdss-dsi-off-command-state = "dsi_hs_mode";
```
https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/SM-G720AX/arch/arm/boot/dts/samsung/msm8916/dsi-panel-s6d2aa0x-hd-video.dtsi#L71-L72

https://github.com/msm8916-mainline/linux-mdss-dsi-panel-driver-generator/commit/1b91d259909af4958f451407885a531f5be1981b

```c
		qcom,mdss-force-clk-lane-hs = <1>;
```
https://github.com/msm8916-mainline/android_kernel_qcom_msm8916/blob/SM-G720AX/arch/arm/boot/dts/samsung/msm8916/dsi-panel-s6d2aa0x-hd-video.dtsi#L94

2022-05-27 08:07 UTC, wonderfulShrineMaidenOfParadise commented on drivers/gpu/drm/panel/msm8916-generated/panel-samsung-s6d2aa0x62-lpm053a250a.c
> +			  MIPI_DSI_MODE_NO_EOT_PACKET | MIPI_DSI_CLOCK_NON_CONTINUOUS;
To be honest I don't understand why I need it, either.

2022-05-27 13:03 UTC, wonderfulShrineMaidenOfParadise commented on drivers/gpu/drm/panel/msm8916-generated/panel-samsung-s6d2aa0x62-lpm053a250a.c
> +			  MIPI_DSI_MODE_NO_EOT_PACKET | MIPI_DSI_CLOCK_NON_CONTINUOUS;
Reworded the commit.

2022-05-28 04:41 UTC, wonderfulShrineMaidenOfParadise commented
Add GPIO vibrator.

2022-05-29 10:40 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8916-samsung-grandmax.dts
> +	};
This seems unused so far

2022-05-29 12:59 UTC, wonderfulShrineMaidenOfParadise commented on drivers/gpu/drm/panel/msm8916-generated/Makefile
> +obj-$(CONFIG_DRM_PANEL_MSM8916_GENERATED) += panel-samsung-s6288a0.o
I would admit, it shouldn't be here.

2022-05-29 13:23 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-grandmax.dts
> +	};
It seems so. Should I drop it?

2022-05-29 13:38 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-samsung-grandmax.dts
> +	};
Funny. After dropping it brightness control works now.

2022-05-29 21:52 UTC, wonderfulShrineMaidenOfParadise commented
- Add `msm8916-samsung-e2015-common.dtsi`, with shared parts:
  - Reserved Memory
  - SM5504 MUIC
  - LIS2HH12 Accelerometer
- Update E7 device tree

2022-05-31 12:01 UTC, wonderfulShrineMaidenOfParadise commented
`/delete-node/ i2c-nfc;` for `msm8916-samsung-grandmax` since it's unavailable on Grand Max series

2022-06-04 11:27 UTC, stephan-gh approved these changes

2022-06-04 12:08 UTC, stephan-gh commented
Pushed to rebase

2022-06-04 12:08 UTC, closed without merging