Piccolo msm8916
msm8916-mainline/linux pull request #251
Opened 2022-11-05 10:08 UTC by a-andre

2022-11-06 19:03 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/Makefile
> +dtb-$(CONFIG_ARCH_QCOM)	+= msm8939-bq-piccolo.dtb
I would like to call this `msm8939-longcheer-l9100` instead for consistency with bq-paella/picmt (longcheer-l8910) and the other ODM-named devices (longcheer-* and wingtech-*). This is highly subjective but I think this better shows the similarity between the devices (for example that bq-paella/picmt and piccolo have mostly the same sensors)

2022-11-06 19:03 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-bq-piccolo.dts
> +		pinctrl-names = "default";
pinctrl-0 missing?

2022-11-06 19:03 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-bq-piccolo.dts
> +		interrupts = <113 IRQ_TYPE_EDGE_FALLING>;
please add pinctrl for this

2022-11-06 19:03 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-bq-piccolo.dts
> +		interrupts = <13 IRQ_TYPE_EDGE_FALLING>;
IRQ_TYPE_LEVEL_LOW is preferred for maxtouch, this should avoid the "enabling RETRIGEN workaround" message in dmesg

2022-11-06 19:03 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-bq-piccolo.dts
> +		compatible = "piccolo,truly-nt35695";
`longcheer,l9100-panel` with my suggestion, we need to add panel detection in lk2nd since there are multiple possible panels iirc

2022-11-06 19:03 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-bq-piccolo.dts
> +	camera_front_flash {
I'd drop this outer node

2022-11-09 09:57 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		reset-gpio = <&msmgpio 12 GPIO_ACTIVE_LOW>;
reset-gpio**s** (-gpio is deprecated in favor of -gpios)

2022-11-09 09:57 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		reset-gpios = <&msmgpio 25 GPIO_ACTIVE_LOW>;
I would add the `backlight-gpios` here (see `qcom,platform-bklight-en-gpio` in piccolo.dts). The panel generator has an option for this.

2022-11-09 09:57 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +	charger: battery@14 {
After adding this you should replace parts of the `&usb` and `&usb_hs_phy` extcon with this, and also add the vbus-supply to `&usb` to enable USB OTG support. See longcheer-l8910 for an example

2022-11-09 09:57 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		pins = "gpio8";
It's strange that in the default-state only gpio49 is configured, while in the sleep-state only gpio8 is configured. Also, the sleep state is only applied if the driver selects it explicitly (usually by calling `pinctrl_pm_select_sleep_state()`). The sgm3140 driver doesn't do that so I'd just omit the sleep state here.

2022-11-09 10:00 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		compatible = "longcheer,l9100-panel";
Can you submit a PR with the lk2nd changes for this?

2022-11-09 21:26 UTC, a-andre commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +	charger: battery@14 {
I'm probably doing something wrong, but when I do that USB (networking) stops working. `dmesg` doesn't show anything, neither on the phone nor on the PC, when I connect both.

2022-11-09 21:29 UTC, a-andre commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		compatible = "longcheer,l9100-panel";
https://github.com/msm8916-mainline/lk2nd/pull/212

2022-11-10 07:44 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +	charger: battery@14 {
You need to add smb1360 to `deviceinfo_modules_initfs` in pmOS, see bq-paella.

2022-11-10 17:41 UTC, a-andre commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +	charger: battery@14 {
That did it.

2022-11-11 08:04 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +&sdhc_1 {
There are several `-supply`s missing here and in `&dsi` and maybe others. Right now everything from `msm8916-pm8916.dtsi` needs to be added to all device DTS on 8939, similar to the idol3 PR. (NOTE: I haven't checked if 8939 uses exactly the same supplies as 8916, maybe some are slightly different)

2022-11-13 12:31 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		backlight-gpios = <&msmgpio 98 GPIO_ACTIVE_LOW>;
Have you tested this? I would expect it to be active-high :thinking:

2022-11-13 12:31 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +	mdss {
please drop the outer node, and add -state suffixes to the nodes below. See related changes in https://git.kernel.org/pub/scm/linux/kernel/git/qcom/linux.git/commit/?h=for-next&id=8b276ca036377a5baa4fd0692b80608f0de8a260

2022-11-13 12:31 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		pinctrl-names = "default", "sleep";
should just have "default" here if there is just a single pinctrl.

2022-11-13 12:31 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		pins = "gpio49";
add gpio8 as well here maybe?

2022-11-13 15:51 UTC, a-andre commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		backlight-gpios = <&msmgpio 98 GPIO_ACTIVE_LOW>;
with active-high, I can turn on/off the back light, but the screen stays black

2022-11-13 15:52 UTC, a-andre commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		pins = "gpio49";
What should change if gpio8 is added and how can I test it?

2022-11-13 15:57 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		pins = "gpio49";
Nothing. The flash should still work.

2022-11-13 15:59 UTC, a-andre commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		pins = "gpio49";
It does :)

2022-11-14 10:11 UTC, stephan-gh commented
Can you update to the `msm8916/6.1-rc5` branch? I added the `msm8939-msm8916.dtsi` include similar to the `msm8916-pm8916.dtsi` used on all the MSM8916 devices, so please:

- `#include "msm8939-pm8916.dtsi"` instead of `#include "msm8939.dtsi"` and `#include "pm8916.dtsi"`
- Drop all the `-supply`s that are already in `msm8939-pm8916.dtsi`
- Change the regulator definitions to be like in MSM8916 devices:
  - `&rpm_requests` -> `&smd_rpm_regulators` (drop the extra subnode)
  - Optional: Can drop the label from all regulator nodes (e.g. `pm8916_s3: s3 { ... }` -> `s3 { ... };`
- See also: https://wiki.postmarketos.org/wiki/MSM8916_Mainlining#Regulators

2022-11-16 19:31 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +
Please try #256, drop this node and see if i2c1~6 still works.

2022-11-21 09:45 UTC, stephan-gh commented
I pushed everything except the smb1360 patch. I'd like more verification for that one, to ensure the settings are really correct and we don't charge the battery incorrectly. @vknecht is already working on this for idol3, you are welcome to help him out if you like :)

2022-12-09 19:01 UTC, stephan-gh requested changes

2022-12-09 19:01 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		interrupts = <62 IRQ_TYPE_EDGE_FALLING>;
It's always IRQ_TYPE_LEVEL_LOW on mainline at the moment (`qcom,stat-pulsed-irq;` is not supported)

2022-12-09 22:47 UTC, a-andre commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		interrupts = <62 IRQ_TYPE_EDGE_FALLING>;
Updated, but not tested yet.

2022-12-10 12:51 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-longcheer-l9100.dts
> +		/* Set by bootloader */
Please also add the `qcom,battery-profile` placeholder already, this will avoid having to resize the DTB in lk2nd since the property can just be overwritten. Maybe copy it exactly like in longcheer-l8910/bq-paella:

```

		/*
		 * Some properties are battery-specific. Battery detection
		 * happens in the bootloader, so it will fill those appropriately
		 * and set status = "okay".
		 */
		status = "disabled";

/* ... */

		qcom,battery-profile = <(-1)>; /* Set by bootloader */
```

2022-12-12 11:11 UTC, stephan-gh commented
Pushed to `msm8916/6.1`, thanks!

2022-12-12 11:11 UTC, closed without merging