Add Lenovo Vibe K5 support
msm8916-mainline/linux pull request #280
Opened 2023-01-15 23:18 UTC by archeYR

* Create WT82918 common device tree which will be used for Lenovo Vibe K5 (A6020a40) and Vibe K5 Plus (A6020a46)
* Add device tree and panel drivers for Lenovo Vibe K5 (A6020a40)
* Vibe K5 Plus device tree/panel drivers can be added later, by someone who owns the device and can test it

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise requested changes
Some minor changes are suggested, please have a look at them.

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +
```suggestion
```

These lines are already included in https://github.com/msm8916-mainline/linux/blob/7468f71a908a82f861c4b10e2896644fc0ecd8df/arch/arm64/boot/dts/qcom/msm8939.dtsi#L289-L291

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +		pinctrl-0 = <&camera_front_flash_default>;
```suggestion
		pinctrl-0 = <&camera_front_flash_default>;
		pinctrl-names = "default";
```

`pinctrl-[0-9]` first then `pinctrl-names`.

https://lore.kernel.org/lkml/20230109110107.3016323-3-nikita@trvn.ru/

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +		enable-gpios = <&msmgpio 31 GPIO_ACTIVE_HIGH>;
```suggestion
		enable-gpios = <&msmgpio 31 GPIO_ACTIVE_HIGH>;
		flash-gpios = <&msmgpio 32 GPIO_ACTIVE_HIGH>;
```

Sort by property names or GPIO pins.

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +		pinctrl-0 = <&gpio_keys_default>;
Ditto. Fix all of them.

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +	monitored-battery = <&battery>;
```suggestion
	monitored-battery = <&battery>;
	status = "okay";
```

`status` should be the last property.
https://lore.kernel.org/lkml/20230109110107.3016323-2-nikita@trvn.ru/

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +	status = "okay";
Ditto. Fix all of them.

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +
```suggestion
```

Stray new line.
https://lore.kernel.org/lkml/20230109110107.3016323-4-nikita@trvn.ru/

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +	gpio_keys_default: gpio-keys-default {
```suggestion
	gpio_keys_default: gpio-keys-default-state {
```

Missing suffix `-state`. Ref: 8b276ca

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +	reg_lcd_en_default: reg-lcd-en-default {
Ditto. Add suffix `-state` for all of them.

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +	pwm_out: mpp4 {
```suggestion
	pwm_out: mpp4-state {
```

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +
Ditto. remove all of them.

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +	};
Interesting schema, but see https://github.com/msm8916-mainline/linux/blob/6e02240872f7a4b62aa8c74676fe33cfbccdbbed/arch/arm64/boot/dts/qcom/msm8916-wingtech-wt88047.dts#L312-L326

Note that the subnodes `*-pins` should be sorted by names or GPIO pins.

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +		pinctrl-2 = <&touchscreen_release>;
Interesting schema, but see https://github.com/msm8916-mainline/linux/blob/6e02240872f7a4b62aa8c74676fe33cfbccdbbed/arch/arm64/boot/dts/qcom/msm8916-wingtech-wt88047.dts#L104-L105

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on drivers/gpu/drm/panel/msm8916-generated/Kconfig
> +
Add the config and dtb to https://github.com/msm8916-mainline/linux-panel-drivers

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8929-wingtech-wt82918.dts
> +#include "msm8939-wingtech-wt82918.dtsi"
What for? Can it be reused by another device?

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +		volume-up {
```suggestion
		button-volume-up {
```
Ref: b08f5cbd69dcd25f5ab2a0798fe3836a97a9d7c6

2023-01-16 00:21 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +		volume-up {
```suggestion
		button-volume-up {
```
Ref: b08f5cbd69dcd25f5ab2a0798fe3836a97a9d7c6

2023-01-16 11:00 UTC, archeYR commented on arch/arm64/boot/dts/qcom/msm8929-wingtech-wt82918.dts
> +#include "msm8939-wingtech-wt82918.dtsi"
It will be also used for Lenovo Vibe K5 Plus (a higher end variant with msm8939v2 and 1080x1920 panels).

2023-01-16 11:47 UTC, wonderfulShrineMaidenOfParadise requested changes

2023-01-16 11:47 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +	touchscreen@38 {
```suggestion
	touchscreen: touchscreen@38 {
```

Would be helpful with `&touchscreen` in children dts.

2023-01-16 11:47 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8929-wingtech-wt82918.dts
> +};
Consider using label `&touchscreen` here.

2023-01-16 11:47 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +			label = "red";
```suggestion
			function = LED_FUNCTION_INDICATOR;
			color = <LED_COLOR_ID_RED>;
```

> This property is deprecated - use 'function' and 'color' properties instead.

Ref: https://github.com/torvalds/linux/blob/master/Documentation/devicetree/bindings/leds/common.yaml#L59

However, choose the properest function. See available functions in https://github.com/torvalds/linux/blob/master/include/dt-bindings/leds/common.h#L43-L104

2023-01-16 11:47 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +			label = "green";
Ditto.

2023-01-16 11:47 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +
Not required, I guess? For good measure, it's worth double checking.

Ref: fab6c02b4099204e2c9e9098a3d9ca638c74e81d

2023-01-16 11:47 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +		};
```suggestion
		reset-pins {
			pins = "gpio12";
			function = "gpio";
			drive-strength = <2>;
			bias-disable;
		};

		touchscreen-pins {
			pins = "gpio13";
			function = "gpio";
			drive-strength = <2>;
			bias-pull-up;
		};
```

Resort.

2023-01-16 12:49 UTC, archeYR commented on drivers/gpu/drm/panel/msm8916-generated/Kconfig
> +
https://github.com/msm8916-mainline/linux-panel-drivers/pull/26

2023-01-16 14:38 UTC, TravMurav commented on drivers/gpu/drm/panel/msm8916-generated/Makefile
> +obj-$(CONFIG_DRM_PANEL_WINGTECH_BOE_HX8394F) += panel-wingtech-boe-hx8394f.o
Please use https://github.com/msm8916-mainline/linux-panel-drivers and only enable the display(s) you can confirm working with the generated driver.

l-p-d will generate a fixup commit for you to replace this one and will also allow us to regenerate the drivers easily at the later date should the need arise.

2023-01-16 14:38 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +	regulator@3e {
Nodes that have address are ordered by the reg.

2023-01-16 14:38 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +		power-source = <PM8916_MPP_VPH>;
```suggestion
		pins = "mpp4";
		function = "digital";
		power-source = <PM8916_MPP_VPH>;
		output-low;
		qcom,dtest = <1>;
```

2023-01-16 16:19 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +		pinctrl-names = "default","sleep";
`sleep` pinctrl works only if some driver explicitly requests it, which is not the case for the MPU6050 driver afaict. I'd remove the sleep state here.

2023-01-16 16:20 UTC, stephan-gh commented
Upstream seems to want less "split commits" lately, can you please squash everything that does not depend on additional driver changes that are not upstream yet? I think you can squash the following commits into one that adds initial support:

- arm64: dts: qcom: msm8939-wingtech-wt82918: Add Wingtech WT82918
- arm64: dts: qcom: msm8929-wingtech-wt82918: Add initial device tree
- arm64: dts: qcom: msm8939-wingtech-wt82918: Add touchscreen 
- arm64: dts: qcom: msm8939-wingtech-wt82918: Add flashlight
- arm64: dts: qcom: msm8939-wingtech-wt82918: Add fuel gauge

2023-01-16 19:21 UTC, stephan-gh reviewed
Looks very good already, thanks! Please also:

- Squash `arm64: dts: qcom: msm8939-wingtech-wt82918: Add accelerometer` (sorry about that one, forgot to include it)
- Rebase to `msm8916/6.2-rc4`

2023-01-16 19:21 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +		bias-pull-down;
These are always kept in output mode, so I think there is no need for a pull here and this can be just `bias-disable` (pull is only relevant in input mode).

2023-01-16 19:21 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +&sound {
FWIW audio setup looks similar to the one of lenovo a6010 (aka msm8916-wingtech-wt86528). Two Awinic speaker amplifiers connected to the left/right headphone output lines (HPHL/HPHR) gives you stereo speakers (see `msm8916-wingtech-wt86528.dts`). Then there is an extra headphones switch (headphones on/off) to ensure that no audio plays on headphones when speakers are used (see `msm8916-wingtech-wt865x8.dtsi`).

You can find the definitions downstream hardcoded deep inside the code:
- GPIOs: https://github.com/msm8916-mainline/linux-downstream/blob/lenovo-vibe-k5/sound/soc/codecs/msm8x16-wcd.h#L37-L39
- Awinic mode: https://github.com/msm8916-mainline/linux-downstream/blob/lenovo-vibe-k5/sound/soc/msm/msm8x16.c#L56

For comparison, same definitions (but different GPIOs) in lenovo-a6010 source code:
- GPIOs: https://github.com/msm8916-mainline/linux-downstream/blob/lenovo-a6010/sound/soc/codecs/msm8x16-wcd.h#L37-L39
- Awinic mode: https://github.com/msm8916-mainline/linux-downstream/blob/lenovo-a6010/sound/soc/msm/msm8x16.c#L56

For HS_US_EU_EN_GPIO it looks like it is suppoed to get enabled when a headphone jack is plugged in, not sure if such functionality exists already. Feel free to defer this one until later, but the speaker stuff should be easy to set up based on the existing approach from lenovo-a6010.

2023-01-16 19:49 UTC, archeYR commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +&sound {
Yes, audio is similar to a6010, but I couldn't find the GPIO pins that they used here. I will try to enable speakers soon. Thanks for the hints. :)

2023-01-18 19:22 UTC, archeYR commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +&sound {
Alright. I tried it with a6010 audio-routing and headphones+all speakers are working, but there are problems:
* Speakers appear to be swapped (eg. "front left" channel outputs on right speaker). Swapping RX1/RX2 [here](https://github.com/msm8916-mainline/alsa-ucm-conf/blob/master/ucm2/codecs/msm8916-wcd/SpeakerHPHLR.conf#L10,L11) fixes this.
* Stereo audio doesn't really work in headphones ("front left" and "front right" channels always output on both speakers in headphones).

Would that be fine for now? Sadly I don't have much time to figure out these problems soon.

2023-01-20 14:45 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +&sound {
> Speakers appear to be swapped (eg. "front left" channel outputs on right speaker). Swapping RX1/RX2 here fixes this.

What is left and right there is a matter of perspective I guess. Are you seeing this with the screen or the back facing you?

> Stereo audio doesn't really work in headphones ("front left" and "front right" channels always output on both speakers in headphones).

Weird, that sounds like a configuration problem and/or something went wrong while switching the audio outputs.

> Would that be fine for now? Sadly I don't have much time to figure out these problems soon.

If you want you can drop the audio commit for now and we can focus on the rest. I would prefer to postpone the audio setup entirely rather than merging half-working changes.

2023-01-20 16:12 UTC, archeYR commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +&sound {
> What is left and right there is a matter of perspective I guess. Are you seeing this with the screen or the back facing you?

From screen side perspective. I also was unsure about this so I compared it with Android, there speakers are in place. 
> Weird, that sounds like a configuration problem and/or something went wrong while switching the audio outputs.

I tried briefly tweaking the alsa ucm configuration for that too, but no luck so far. 
> If you want you can drop the audio commit for now and we can focus on the rest. I would prefer to postpone the audio setup entirely rather than merging half-working changes.

Sure. Dropped the audio commit for now. Will try to add fully working audio setup in another PR then.

2023-01-30 14:52 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8929-wingtech-wt82918.dts
> +/* MSM8929 GPU clocks up to 465MHz */
I think you should put this into a `msm8929.dtsi` that you include additionally, since it's not really specific to your device but to the SoC

2023-01-30 14:52 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +		ocv-capacity-celsius = <(-20) 0 25 40 60>;
The pm8916 bms driver does not support separate tables for temperatures atm (and even if it did it's unclear if it would actually provide any advantage, given that the driver is already very inaccurate at the moment). Can you remove all tables except the 25°C one for now?

2023-01-31 20:08 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8929-wingtech-wt82918.dts
> +	compatible = "wingtech,wt82918", "qcom,msm8929";
I guess this should be `wingtech,wt82918hd`? Using wt82918 would clash with the 8939 version which definitely needs a different compatible. Maybe also change this in the file name for best clarity (although the file name is unique given that it has the msm8929-)

2023-01-31 20:08 UTC, stephan-gh commented on arch/arm64/boot/dts/qcom/msm8939-wingtech-wt82918.dtsi
> +		charge-term-current-microamp = <100000>;
Please drop this property for now until it's clear how the charger driver will look like. (Shouldn't be needed for the fuel gauge)

2023-03-25 17:01 UTC, TravMurav reviewed
Tiny nitpick, otherwise looks good at the first glance

2023-03-25 17:04 UTC, TravMurav approved these changes

2023-04-07 18:17 UTC, stephan-gh approved these changes

2023-04-11 07:39 UTC, stephan-gh commented
Added to `wip/msm8916/6.3-rc6`, thanks!

2023-04-11 07:39 UTC, closed without merging

2023-04-24 08:53 UTC, stephan-gh commented
@archeYR Can you make a merge request at https://gitlab.com/postmarketOS/pmaports with your device package? Or are you using a different distro?

2023-04-24 20:17 UTC, archeYR commented
> @archeYR Can you make a merge request at https://gitlab.com/postmarketOS/pmaports with your device package? Or are you using a different distro?

Done.
https://gitlab.com/postmarketOS/pmaports/-/merge_requests/4036