arm64: dts: qcom: msm8916-lenovo-phab: add device
msm8916-mainline/linux pull request #287
Opened 2023-02-15 22:40 UTC by k1gen

2023-02-16 11:07 UTC, stephan-gh commented
Please read the contribution guidelines: https://github.com/msm8916-mainline/linux/blob/master/CONTRIBUTING.md regarding the `Signed-off-by` line. Doing a fix-up commit doesn't work, you need to squash it into your other commit.

2023-02-16 16:23 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +		pinctrl-0 = <&gpio_keys_default>;
Right now the preference is to have -names last. You have them mixed across the file, please reorder. (you may find some inconsistency for those minor rules across the dts files since already-upstream files use the old style. We try to follow the modern recommendations for newly added trees.)

Please fix all occurrences.

2023-02-16 16:23 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +		volume-up {
Please check the dt schema docs for the acceptable name format of this node.

2023-02-16 16:23 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +	status = "okay";
It's preferred for status to be always last. Multiple occurrences.

2023-02-16 16:23 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +	usb_id_default: usb-id-default {
node name must end with -state as per the schema. Check everywhere.

2023-02-16 16:23 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +	mdss {
Please un-group this.

2023-02-16 16:23 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +
Please remove this newline. Multiple occurrences.

2023-02-16 16:23 UTC, TravMurav commented on drivers/gpu/drm/panel/msm8916-generated/Makefile
> +obj-$(CONFIG_DRM_PANEL_LENOVO_PHAB_PANEL) += panel-lenovo-phab-panel.o
If you used the linux-panel-drivers script, please don't squash the commit it creates into the wrong place. Your dt commits must only affect the dt file.

2023-02-16 16:23 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +// SPDX-License-Identifier: GPL-2.0-only
I'd really appreciate a commit description for this commit. You can see an example in a history of some other device, i.e.

https://github.com/msm8916-mainline/linux/commit/55056b229189be2b4b8e636f0566a0b5bfd3c8f8
https://github.com/msm8916-mainline/linux/commit/16e8e8072108426029f0c16dff7fbe77fae3df8f

2023-02-16 18:11 UTC, wonderfulShrineMaidenOfParadise requested changes

2023-02-16 18:11 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +	qcom,platform-reset-gpio = <&msmgpio 25 0>;
This doesn't look right when you have

https://github.com/msm8916-mainline/linux/pull/287/files#diff-f7a8251da41f4f4b8cfde1a6739fd464d955bdd739e97d8e7524f0c045dbad8bR94

2023-02-16 18:11 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +	qcom,platform-enable-gpio = <&msmgpio 109 0>;
Use `regulator-fixed` instead.
https://github.com/torvalds/linux/commit/4b20d4705a213f8c272456dc1e85554d013c33b9#diff-aa46666e382638ea94e6862c192ff2ed31c998f39f57d3f5bb800aa818c86478R11-R22

2023-02-16 18:11 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +		mdss_sleep: mdss-sleep {
```suggestion
		};

		mdss_sleep: mdss-sleep {
```

A newline between 2 nodes.

2023-02-16 22:12 UTC, wonderfulShrineMaidenOfParadise commented on drivers/gpu/drm/panel/msm8916-generated/Makefile
> +obj-$(CONFIG_DRM_PANEL_LENOVO_PHAB_PANEL) += panel-lenovo-phab-panel.o
https://github.com/msm8916-mainline/linux-panel-drivers
You also need to add your config and dtb here.

2023-02-17 17:53 UTC, wonderfulShrineMaidenOfParadise reviewed
It's nice to keep a good coding style, which might help you with debugging.

2023-02-17 17:53 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +	iris {
```suggestion
	status = "okay";

	iris {
```

Always have a newline between last property and first node.

2023-02-17 17:53 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +	tas2552: tas2552@40 {
```suggestion
	status = "okay";

	tas2552: tas2552@40 {
```

2023-02-17 17:53 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +};
Pinctrl nodes are preferred to be put in the bottom of a dts. You can put this after `&msmgpio`.

2023-02-17 17:53 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +	model = "lenovo-phab";
Not a valid model. See https://github.com/msm8916-mainline/alsa-ucm-conf/tree/master/ucm2 for available models.

2023-02-17 17:53 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +	codec {
```suggestion
	status = "okay";

	codec {
```

2023-02-17 17:53 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +		};
```suggestion
		reset-pins {
			pins = "gpio12";
			function = "gpio";
			drive-strength = <2>;
			bias-disable;
		};

		touchscreen-pins {
			pins = "gpio13";
			function = "gpio";
			drive-strength = <2>;
			bias-pull-up;
		};
```

Sort nodes by alphabetical order or GPIO pins.

2023-02-17 17:53 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +	qcom,platform-reset-gpio = <&msmgpio 25 GPIO_ACTIVE_HIGH>;
```suggestion
```

https://github.com/msm8916-mainline/linux/pull/287/files#diff-f7a8251da41f4f4b8cfde1a6739fd464d955bdd739e97d8e7524f0c045dbad8bR148

2023-02-17 17:53 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +	panel@0 {
```suggestion
	pinctrl-names = "default", "sleep";

	panel@0 {
```

2023-02-17 17:53 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +	touchscreen@38 {
```suggestion
	status = "okay";

	touchscreen@38 {
```

2023-02-17 17:53 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +        usb_vbus: usb-vbus {
```suggestion
	usb_vbus: usb-vbus {
```

2023-02-17 17:53 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +        compatible = "summit,smb358";
```suggestion
		compatible = "summit,smb358";
```

Use tabs instead, and fix the indents.

2023-02-17 17:53 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +		label = "GPIO Buttons";
```suggestion
		label = "GPIO Buttons";

```

2023-02-17 17:53 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +		port {
```suggestion
		reset-gpios = <&msmgpio 25 GPIO_ACTIVE_LOW>;

		port {
```

2023-02-20 18:53 UTC, wonderfulShrineMaidenOfParadise requested changes

2023-02-20 18:53 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +	pwm_out: mpp4 {
```suggestion
	pwm_out: mpp4-state {
```

Same with GPIO pinctrl.

2023-02-23 16:40 UTC, k1gen reviewed
review request

2023-02-23 16:52 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +		//charge-full-design-microamp-hours = <4250000>;
Either un-comment or remove.

2023-02-23 16:52 UTC, TravMurav commented on arch/arm64/boot/dts/qcom/msm8916-lenovo-phab.dts
> +	reserved-memory {
This node is special, please move right after "chosen"

2023-02-23 17:18 UTC, k1gen commented
Closing this PR, will open new one with cleaner commit history and merging from personal branch

2023-02-23 17:18 UTC, closed without merging