arm64: dts: qcom: Add device tree for Samsung Galaxy Tab A 9.7 Wifi (2015)
msm8916-mainline/linux pull request #30
Opened 2019-08-31 18:03 UTC by jja2000

Samsung Galaxy Tab A 9.7 Wifi (2015) (SM-T550) is a tablet using the MSM8916 SoC released in 2015.

Add a device tree for gt510wifi with initial support for:

SDHCI (internal and external storage)
USB Device Mode
UART (Untested)
Regulators

2019-08-31 18:05 UTC, stephan-gh requested changes

2019-08-31 18:05 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/apq8016-samsung-gt510wifi.dts
> +	model = "Samsung Galaxy Tab A 9.7 Wifi (2015) (SM-T550)";
```suggestion
	model = "Samsung Galaxy Tab A 9.7 WiFi (2015) (SM-T550)";
```

2019-08-31 18:05 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/apq8016-samsung-gt510wifi.dts
> +	// FIXME: Use extcon device provided by charger driver when available
```suggestion
	// FIXME: Use extcon device provided by MUIC driver when available
```

or `extcon` I guess, whatever you prefer. It's not directly related to the charger on this device.

2019-08-31 18:46 UTC, stephan-gh requested changes
wrap the commit message at about ~80 chars, i.e. break up:

```
Samsung Galaxy Tab A 9.7 WiFi (2015) (SM-T550) is a tablet using the APQ8016 SoC released in 2015.
```

A good measure are the comments Git displays below the commit message in the editor when you make a  commit message. They're properly line-wrapped.

```
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
```

2019-08-31 18:46 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/apq8016-samsung-gt510wifi.dts
> +
one blank line is enough

2019-08-31 20:37 UTC, stephan-gh approved these changes

2019-08-31 20:43 UTC, Minecrell commented
Applied manually with a small update of the commit message. I think I may have suggested the wrong max line length, try ~75 for future patches (also see [Submitting patches: the essential guide to getting your code into the kernel](https://www.kernel.org/doc/html/latest/process/submitting-patches.html))

2019-08-31 20:43 UTC, closed without merging

2025-09-06 16:20 UTC, lynch-mob88 reviewed
.

2025-09-06 16:20 UTC, lynch-mob88 commented on arch/arm64/boot/dts/qcom/Makefile
>  # SPDX-License-Identifier: GPL-2.0
.