msm8909: add device tree for zte sapphire (based on acer-t01)
msm8916-mainline/linux pull request #380
Opened 2024-11-17 01:51 UTC by kclinx

Device tree for ZTE N818s (sapphire), based on acer-t01

Tested (working):

USB Networking
Display (with simplefb)
Wifi:

Works in 802.11n mode only
Not working:

Touchscreen, volume buttons, probably everything else

Re-Opened due to me not knowing how to use git properly; added sign-off

2024-11-17 03:49 UTC, wonderfulShrineMaidenOfParadise requested changes

2024-11-17 03:49 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +};
```suggestion
&pm8909_usbin {
	status = "okay";
};

&pm8909_vib {
	status = "okay";
};

&sdhc_1 {
	status = "okay";
};

&sdhc_2 {
	non-removable;
	status = "okay";
};
```

abcde...pqrs...uv...

2024-11-17 03:49 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +	};
No idea why you need it when it doesn't exist in acer-t01

2024-11-17 03:49 UTC, wonderfulShrineMaidenOfParadise commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +#include <dt-bindings/leds/common.h>
Unused for now.

2024-11-17 03:52 UTC, kclinx commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +	};
It was not working before I added it.  Several of the guides on-line, and some people from the porting chat suggested it.

I'm not sure either though

2024-11-17 03:53 UTC, kclinx commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +#include <dt-bindings/leds/common.h>
yeah.  I can get rid of them if you want

2024-11-17 04:28 UTC, kclinx commented
I accepted the suggestion from the web interface and created another check issue for sign off, so I merged, squashed, and force pushed to fix it.  Hopefully this works now

2024-11-17 05:19 UTC, TravMurav commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +	model = "ZTE sapphire";
```suggestion
	model = "ZTE N818s";
```

2024-11-17 05:19 UTC, TravMurav commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +			reg = <0x83200036 (480 * 800 * 3)>;
this is a really weird address... It doesn't match the cont_splash_mem, and you don't link this node to that one either.... I'm rather confused what's going on there, could you confirm what lk2nd says is the memory region? Do you use lk2nd's simplefb facilities to fixup this?

2024-11-17 05:30 UTC, kclinx commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +			reg = <0x83200036 (480 * 800 * 3)>;
[130] MDP continuous splash detected: DMA_P, base: 0x83200036, stride: 1440, size: 480x800, out: (0,0), config: 0x1800bf (format: 0x0)

This is a debug message from lk2nd.  I used it to get the base address of the framebuffer.  The address on the reserved memory region came from the downstream dts

2024-11-17 05:31 UTC, kclinx commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +			reg = <0x83200036 (480 * 800 * 3)>;
I have tried using 0x83200000, and the output gets torn on one side.  With 0x83000000, there is no display output at all

2024-11-17 06:02 UTC, TravMurav commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +			reg = <0x83200036 (480 * 800 * 3)>;
lk2nd's debug information will be correct then, but I'd expect you to fix reserved memory in accordance (same address/size as simplefb node) and add memory-region then

https://elixir.bootlin.com/linux/v6.12-rc7/source/Documentation/devicetree/bindings/display/simple-framebuffer.yaml#L71

2024-11-17 06:06 UTC, kclinx commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +			reg = <0x83200036 (480 * 800 * 3)>;
I tried to, but that causes it to break:
```
[    0.811064] ------------[ cut here ]------------
[    0.813940] WARNING: CPU: 3 PID: 1 at arch/arm/mm/ioremap.c:293 __arm_ioremap_pfn_caller+0xe4/0x1bc
[    0.818700] Modules linked in:
[    0.827457] CPU: 3 PID: 1 Comm: swapper/0 Not tainted 6.6.0-msm8916 #10
[    0.830560] Hardware name: Generic DT based system
[    0.837079]  unwind_backtrace from show_stack+0x18/0x1c
[    0.841932]  show_stack from dump_stack_lvl+0x40/0x4c
[    0.847054]  dump_stack_lvl from __warn+0x84/0x144
[    0.852261]  __warn from warn_slowpath_fmt+0x1bc/0x1c4
[    0.856950]  warn_slowpath_fmt from __arm_ioremap_pfn_caller+0xe4/0x1bc
[    0.862073]  __arm_ioremap_pfn_caller from __arm_ioremap_caller+0x50/0x58
[    0.868583]  __arm_ioremap_caller from devm_ioremap_wc+0x4c/0x80
[    0.875529]  devm_ioremap_wc from simpledrm_probe+0xb6c/0xe18
[    0.881603]  simpledrm_probe from platform_probe+0x64/0xbc
[    0.887246]  platform_probe from really_probe+0xd8/0x3d4
[    0.892625]  really_probe from __driver_probe_device+0x94/0x1e8
[    0.898097]  __driver_probe_device from driver_probe_device+0x38/0xd4
[    0.903739]  driver_probe_device from __driver_attach+0xc0/0x1b8
[    0.910336]  __driver_attach from bus_for_each_dev+0x84/0xd4
[    0.916413]  bus_for_each_dev from bus_add_driver+0xf8/0x1fc
[    0.922054]  bus_add_driver from driver_register+0x88/0x120
[    0.927696]  driver_register from do_one_initcall+0x50/0x268
[    0.932992]  do_one_initcall from kernel_init_freeable+0x20c/0x268
[    0.938896]  kernel_init_freeable from kernel_init+0x18/0x138
[    0.944884]  kernel_init from ret_from_fork+0x14/0x28
[    0.950696] Exception stack(0xf0821fb0 to 0xf0821ff8)
[    0.955737] 1fa0:                                     00000000 00000000 00000000 00000000
[    0.960778] 1fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[    0.968937] 1fe0: 00000000 00000000 00000000 00000000 00000013 00000000
[    0.977162] ---[ end trace 0000000000000000 ]---
[    0.983634] simple-framebuffer: probe of 83200036.framebuffer failed with error -12

```

2024-11-17 06:10 UTC, TravMurav commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +			reg = <0x83200036 (480 * 800 * 3)>;
does it work if you use 0x83200000?

2024-11-17 06:10 UTC, kclinx commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +			reg = <0x83200036 (480 * 800 * 3)>;
However, I could change it to this:
```dts
        reserved-memory {
		cont_splash_mem: memory@83200000 {
			reg = <0x83200000 0x119424>;
			no-map;
		};
	};
```

2024-11-17 06:11 UTC, kclinx commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +			reg = <0x83200036 (480 * 800 * 3)>;
yes

2024-11-17 06:11 UTC, kclinx commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +			reg = <0x83200036 (480 * 800 * 3)>;
Shall I change to that then?

2024-11-17 06:11 UTC, TravMurav commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +			reg = <0x83200036 (480 * 800 * 3)>;
do you use simplefb or simpledrm?

2024-11-17 06:12 UTC, kclinx commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +			reg = <0x83200036 (480 * 800 * 3)>;
simple-framebuffer, but the memory is allocated by simpledrm

2024-11-17 06:29 UTC, TravMurav commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +			reg = <0x83200000 0x119424>;
```suggestion
			reg = <0x83200000 (0x36 + (480 * 800 * 3))>;
```

2024-11-17 06:29 UTC, TravMurav commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +
Could you please add a comment here that the bootloader is stupid and doesn't put fb at an aligned address so we can't have memory-region here. Perhaps also a comment in the reserved memory node, why we have +0x36

2024-11-17 06:29 UTC, kclinx commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +			reg = <0x83200000 0x119424>;
the difference is 36 bytes, not 0x36

2024-11-17 06:30 UTC, kclinx commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +
sure

2024-11-17 06:38 UTC, TravMurav commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +			// downstream bootloader is stupid, and gives us this ugly unaligned memory region
DT code style upstream uses C style (/* */) comments, also please fold at 80/100. Also I wanted this comment to explain that the node /should've/ had memory-region property but can't due to a quirk.

2024-11-17 06:51 UTC, TravMurav commented on arch/arm/boot/dts/qcom/qcom-msm8909-zte-sapphire.dts
> +
https://elixir.bootlin.com/linux/v6.11.8/source/arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts#L26-L37

this is the expected style, sorry for not clarifying

2024-11-17 07:02 UTC, TravMurav commented
Also could you please re-target and re-test against 6.12-rc7 branch

2024-11-19 04:15 UTC, wonderfulShrineMaidenOfParadise commented
> Also could you please re-target and re-test against 6.12-rc7 branch

[6.12](https://github.com/torvalds/linux/tree/v6.12) is out :tada:

2024-11-19 04:17 UTC, kclinx commented
> > Also could you please re-target and re-test against 6.12-rc7 branch
> 
> [6.12](https://github.com/torvalds/linux/tree/v6.12) is out 🎉

that was quick, I'll re-target that.... just as I had it working on 6.12-rc7 too

2024-11-19 04:37 UTC, kclinx commented
re-target for 6.12-rc7 branch: https://github.com/msm8916-mainline/linux/pull/381

2024-11-19 04:37 UTC, closed without merging