draft for oppo-a51f
msm8916-mainline/linux pull request #99
Opened 2020-08-18 09:37 UTC by Hinokami-Kagura

for oppo-a51f with Linux kernel 5.7.1 mainline, but it can't boot, maybe somewhere need modify...XD

2020-08-18 09:43 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +            cd-gpios = <0x48 0x26 0x00>;
This looks totally broken. It should be `&msmgpio` followed by some gpio number in the example.

I recommend that you look at the downstream source, not the binary dtb: https://github.com/oppo-source/R7plus-5.1-kernel-source/blob/master/arch/arm/boot/dts/15009/msm8916-mtp.dtsi

2020-08-18 09:45 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +// FIXME: Verify all regulators with downstream
remove todo, looks fine

2020-08-18 09:48 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +// TODO (wiki): Explain setup of dummy extcon device to make USB work
It looks like you have an usbid-gpio, please set that up similar to bq-paella:

https://github.com/msm8916-mainline/linux/blob/1d2ab0d6ec15366e9b382421630c32387a3f2157/arch/arm64/boot/dts/qcom/msm8916-bq-paella.dts#L222-L227

https://github.com/msm8916-mainline/linux/blob/1d2ab0d6ec15366e9b382421630c32387a3f2157/arch/arm64/boot/dts/qcom/msm8916-bq-paella.dts#L123-L138

2020-08-19 03:41 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +// FIXME: Verify all regulators with downstream
OK, removed.

2020-08-19 06:51 UTC, Minecrell requested changes

2020-08-19 06:51 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	        cd-gpios = <&msmgpio 38 0x0>;
indentation is weird here, please use tabs. Also `0x0 = GPIO_ACTIVE_HIGH`

```suggestion
	        cd-gpios = <&msmgpio 38 GPIO_ACTIVE_HIGH>;
```

see

https://github.com/msm8916-mainline/linux/blob/1d2ab0d6ec15366e9b382421630c32387a3f2157/include/dt-bindings/gpio/gpio.h#L13-L15

2020-08-20 13:39 UTC, Minecrell commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	        cd-gpios = <&msmgpio 38 GPIO_ACTIVE_HIGH>;
there are still some spaces here instead of tabs

2020-08-24 09:38 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	        cd-gpios = <&msmgpio 38 GPIO_ACTIVE_HIGH>;
OK, modified!

2020-08-26 08:27 UTC, Minecrell commented
Hi @Hinokami-Kagura. The indentation is still wrong in several places. Please make sure you use tabs consistently.
Also, please make commits with proper commit titles (see other commits in this repository as example).

The changes for the display panel should be in a separate commit later, so I would suggest that you remove them for now and finish up the base dts first. Let me know if you need any help. Thanks.

2020-08-27 04:50 UTC, Hinokami-Kagura commented on arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
> +	        cd-gpios = <&msmgpio 38 GPIO_ACTIVE_HIGH>;
Seems I need to use terminal nano for avoiding the "auto-filling" feature by GUI editor...XD

2020-08-27 04:54 UTC, Hinokami-Kagura reviewed
removed the panel and dsi for initial only

2020-08-27 04:57 UTC, closed without merging